---
title: "Self-Discipline"
author: "Sung Inkyung"
date: '2021 12 15'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggfx)
library(ggtext)
library(lubridate)
library(paletteer)
library(showtext)

font_add_google("Permanent Marker")
showtext_opts(dpi = 320)
showtext_auto(enable = TRUE)

#2Timothy1:7 "For the Spirit God gave us does not make us timid, but gives us power, love and self-discipline"
```


```{r}
drought <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-07-20/drought.csv')

df <- drought %>%
  mutate(start_year = year(valid_start)) %>% 
  filter(stat_fmt == 2) %>%
  select(-area_total, -pop_pct, -pop_total) %>%
  pivot_wider(names_from = "drought_lvl",
              values_from = "area_pct") %>%
  mutate(drought = D0 + D1 + D2 + D3 + D4,
         no_drought = None) %>%
  select(state_abb, valid_start, start_year,
         drought, no_drought) %>%
  pivot_longer(drought:no_drought,
               names_to = "drought",
               values_to = "area_pct") %>%
  mutate(drought = factor(drought, levels = c("no_drought", "drought")))

```

```{r}
plot <- ggplot() +
  as_reference(geom_text(aes(x = 2002, y = 1,
                             label = "P O W E R\nL O V E\nSELF-DISCIPLINE"),
                         size = 30, 
                         hjust = 0),
                         id = 'text') +
  with_blend(geom_tile(data = df, 
                       aes(x = start_year, y = 1, fill = area_pct)),
             bg_layer = "text",
             blend_type = "in",
             id = "blended") +
  with_shadow("blended", sigma = 5) +
  scale_fill_paletteer_c("ggthemes::Red-Black Diverging") +
  scale_x_continuous(limits = c(2000, 2021),
                     expand = c(0, 0)) +
  labs(x = "",
       y = "",
       caption = "**Data**: Drought Montior | **Graphic**: Sung Inkyung") +
  theme_void() +
  theme(legend.position = "none",
        plot.caption = element_markdown(size = 10,
                                        margin = margin(r = 10))) 

ggsave("Self-Discipline.png", width = 30, height = 20, units = "cm")
```

