---
title: "0212 KakaoTalk daily words "
author: "Sung Inkyung"
date: '2022 2 12'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lubridate)
library(ggtext)
library(glue)
library(showtext)

font_add_google("Cinzel")
font_add_google("Barlow")

showtext_opts(dpi = 300)
showtext_auto()
```

```{r}
df <- tribble(
~id, ~date, ~book, ~word,
1, "2021-01-14\n2021-07-05\n2021-10-06\n2022-01-25", "Psalms 54:4", "Surely God is my help; the Lord is the one who sustains me",
2, "2021-02-08\n2021-05-06\n2021-06-07\n2022-01-05", "Psalms 37:4", "Take delight in the LORD, and he will give you the desires of your heart",
3, "2021-03-09\n2021-03-29\n2021-08-25\n2021-10-28", "Psalms 90:14", "Satisfy us in the morning with your unfailing love, that we may sing for joy and be gald all our days",
4, "2021-04-07\n2021-06-15\n2021-09-13\n2021-11-24", "Psalms 121:7", "The LORD will keep you from all harm -- he will watch over your life"
)
```


```{r}
label_segments <- tibble(
  label = glue("*{df$word}*<br /><span style = 'font-family: Cinzel; font-size: 12px; color: gray15'>**{df$book}**</span>"),
  x = df$id * 15,
  xend = x + 1.5 * rep(c(1, -1), length.out = 4),
  y = 1,
  yend = 1 * rep(c(0.5, 1.5), length.out = 4),
  x2 = xend + 6 * rep(c(1, -1), length.out = 4),
  hjust = rep(c(0.03, 0.45), length.out = 4),
  vjust = rep(c(0.95, 0.07), length.out = 4)
)
```

```{r}
plot <-  
  ggplot(data = df, aes(x = id *15, y = 1)) +
  geom_segment(data = label_segments,
               aes(x = x, y = y,
                   xend = xend, yend = yend),
               lineend = "round",
               color = "gray65", size = 0.75) +
  geom_segment(data = label_segments,
               aes(x = xend, y = yend, xend = x2, yend = yend),
               lineend = "round",
               color = "gray70", size = 0.75) +
  geom_line(color = "#1d3557", size = 2) +
  geom_point(size = 6, stroke = 1.5, fill = alpha("#47b1af",  0.9), color = "#f90c71", shape = 21) +
  geom_text(aes(label = date), 
            nudge_y = 0.15 * rep(c(1, -1), length.out = 4),
            family = "Barlow", size = 3.5, lineheight = 0.9) +
  geom_textbox(data = label_segments, 
               aes(x = xend, y = yend, label = label,
                   hjust = hjust, vjust = vjust),
               width = unit(70, "mm"), box.color = NA, fill = NA,
               size = 3, family = "Cinzel", lineheight = 1.1) +
  scale_x_continuous(limits = c(10, 65)) +
  scale_y_continuous(limits = c(0, 2)) +
  coord_cartesian(clip = "off") +
  labs(title = "Daily Bread from Mrs. Yoon MinSook",
       subtitle = "Words that were repeated 4 times among bible messages that\nMs.Yoon have sent through KakaoTalk every day since 2019",
       caption = "Source: KakaoTalk from Ms.Yoon | Graphic: Sung Inkyung") +
  theme_void() +
  theme(plot.background = element_rect(fill = "#f7e600", color = NA),
        plot.title = element_text(family = "Barlow",
                                  size = 24,
                                  face = "bold",
                                  hjust = 0.5,
                                  margin = margin(t = 15, b = 7)),
        plot.subtitle = element_text(family = "Barlow",
                                  size = 13,
                                  hjust = 0.5),
        plot.caption = element_text(family = "Barlow",
                                  size = 10,
                                  hjust = 0.5,
                                  color = "gray35"),
        plot.margin = margin(10, 10, 10, 10))

ggsave("0212_KakaoTalk_DailyWords.png", width = 30, height = 20, units = "cm")
  
```

