---
title: "Prefix"
author: "Sung Inkyung"
date: '2021 12 31'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Source[RecreationThursday by @quite_gray] (https://pastebin.com/STXAk78n)
```{r}
#recreationthursday 2021 10 09
#Escher wrapping paper
library(showtext)
library(tidyverse)
 
 
#font
font_add_google("Poiret One", "poiret")
 
 
#graphic
showtext_auto()
showtext_opts(dpi = 72)

```


```{r}
#block
p1 <- ggplot() +
  scale_y_continuous(limits = c(0, 6)) +
  scale_x_continuous(limits = c(0, 4)) +
  coord_fixed(expand = FALSE) +
  theme_void()
 
 
#tiles
tile_grid <- expand_grid(
  x = c(0.5, 1.5, 2.5, 3.5),
  y = c(0.5, 1.5, 2.5, 3.5, 4.5, 5.5)
) %>%
  mutate(fill = c(0,0,0,0,1,0,
                  1,1,1,1,1,1,
                  1,0,0,1,1,0,
                  0,0,0,0,0,0) %>%
           as.character
  )
 
 
p2 <- p1 +
  geom_tile(data = tile_grid,
            aes(x, y, fill = fill),
            show.legend = FALSE) +
  scale_fill_manual(values = c("#FAFAFA", "#0A0A0A"))
 
 
#add text
p3 <- p2 +
  geom_text(aes(0.5, 5.5, label = "EN"),
            family = "poiret",
            size = 30,
            angle = 0,
            colour = "#0A0A0A") +
  geom_text(aes(0.5, 4.5, label = "EN"),
            family = "poiret",
            size = 30,
            angle = 180,
            colour = "#FAFAFA") +
  geom_text(aes(1.5, 4.85, label = "INTER"),
            family = "poiret",
            size = 25,
            angle = 270,
            colour = "#FAFAFA") +
  geom_text(aes(2.5, 3.5, label = "RE"),
            family = "poiret",
            size = 25,
            angle = 0,
            colour = "#FAFAFA") +
  geom_text(aes(2.5, 4.5, label = "EN"),
            family = "poiret",
            size = 30,
            angle = 90,
            colour = "#FAFAFA") +
  geom_text(aes(3, 5.5, label = "INTER"),
            family = "poiret",
            size = 25,
            angle = 0,
            colour = "#0A0A0A") +
  geom_text(aes(3.5, 3.5, label = "RE"),
            family = "poiret",
            size = 25,
            angle = 90,
            colour = "#0A0A0A") +
  geom_text(aes(1.5, 2.5, label = "RE"),
            family = "poiret",
            size = 25,
            angle = 270,
            colour = "#FAFAFA") +
  geom_text(aes(2.5, 2.5, label = "RE"),
            family = "poiret",
            size = 25,
            angle = 180,
            colour = "#0A0A0A") +
  geom_text(aes(3.5, 1.15, label = "INTER"),
            family = "poiret",
            size = 25,
            angle = 90,
            colour = "#0A0A0A") +
  geom_text(aes(2, 0.5, label = "INTER"),
            family = "poiret",
            size = 25,
            angle = 180,
            colour = "#FAFAFA") +
  geom_text(aes(2.5, 1.5, label = "EN"),
            family = "poiret",
            size = 30,
            angle = 270,
            colour = "#0A0A0A")
 
 
#points and "o"s
point_grid <- tibble(
  x = c(1.5, 1.5, 3.5, 3.5),
  y = c(1.5, 3.5, 2.5, 4.5),
  type = c("A", "B", "C", "D")
)
 
 
p4 <- p3 +
  geom_point(data = point_grid,
             aes(x, y, fill = type, colour = type),
             shape = 21,
             stroke = 1.25,
             size = 8,
             show.legend = FALSE) +
  scale_fill_manual(values = c("#FAFAFA", "#0A0A0A", "#AD5B78", "#FAFAFA", "#0A0A0A", "#4A6274")) +
  scale_colour_manual(values = c("#0A0A0A", "#0A0A0A", "#FAFAFA", "#FAFAFA"))
 
 
 
#lines
block_1 <- p4 +
  geom_segment(aes(x = 0.05, xend = 0.95, y = 5.05, yend = 5.05),
               size = 0.6,
               colour = "#0A0A0A") +
  geom_segment(aes(x = 0.05, xend = 0.95, y = 4.95, yend = 4.95),
               size = 0.6,
               colour = "#FAFAFA") +
  geom_segment(aes(x = 1.075, xend = 1.075, y = 0.05, yend = 5.95),
               size = 0.6,
               colour = "#FAFAFA") +
  geom_segment(aes(x = 1, xend = 2.9, y = 3.1, yend = 3.1),
               size = 0.6,
               colour = "#FAFAFA") +
  geom_segment(aes(x = 2.1, xend = 4, y = 2.9, yend = 2.9),
               size = 0.6,
               colour = "#0A0A0A") +
  geom_segment(aes(x = 2.1, xend = 4, y = 5.1, yend = 5.1),
               size = 0.6,
               colour = "#0A0A0A") +
  geom_segment(aes(x = 2.05, xend = 2.05, y = 1.1, yend = 1.9),
               size = 0.6,
               colour = "#0A0A0A") +
  geom_segment(aes(x = 3.95, xend = 3.95, y = 0.1, yend = 4.9),
               size = 0.6,
               colour = "#0A0A0A") +
  geom_segment(aes(x = 2.95, xend = 2.95, y = 4.1, yend = 4.9),
               size = 0.6,
               colour = "#FAFAFA")
 
 
##block 2 ----
p1 <- ggplot() +
  scale_y_continuous(limits = c(0, 6)) +
  scale_x_continuous(limits = c(0, 4)) +
  coord_fixed(expand = FALSE) +
  theme_void()
 
 
#tiles
tile_grid <- expand_grid(
  x = c(0.5, 1.5, 2.5, 3.5),
  y = c(0.5, 1.5, 2.5, 3.5, 4.5, 5.5)
) %>%
  mutate(fill = c(0,0,0,0,1,0,
                  1,1,1,1,1,1,
                  1,0,0,1,1,0,
                  0,0,0,0,0,0) %>%
           as.character
  )
 
 
p2 <- p1 +
  geom_tile(data = tile_grid,
            aes(x, y, fill = fill),
            show.legend = FALSE) +
  scale_fill_manual(values = c("#0A0A0A", "#FAFAFA"))
 
 
#add text
p3 <- p2 +
  geom_text(aes(0.5, 5.5, label = "EN"),
            family = "poiret",
            size = 30,
            angle = 0,
            colour = "#FAFAFA") +
  geom_text(aes(0.5, 4.5, label = "EN"),
            family = "poiret",
            size = 30,
            angle = 180,
            colour = "#0A0A0A") +
  geom_text(aes(1.5, 4.85, label = "INTER"),
            family = "poiret",
            size = 25,
            angle = 270,
            colour = "#0A0A0A") +
  geom_text(aes(2.5, 3.5, label = "RE"),
            family = "poiret",
            size = 25,
            angle = 0,
            colour = "#0A0A0A") +
  geom_text(aes(2.5, 4.5, label = "EN"),
            family = "poiret",
            size = 30,
            angle = 90,
            colour = "#0A0A0A") +
  geom_text(aes(3, 5.5, label = "INTER"),
            family = "poiret",
            size = 25,
            angle = 0,
            colour = "#FAFAFA") +
  geom_text(aes(3.5, 3.5, label = "RE"),
            family = "poiret",
            size = 25,
            angle = 90,
            colour = "#FAFAFA") +
  geom_text(aes(1.5, 2.5, label = "RE"),
            family = "poiret",
            size = 25,
            angle = 270,
            colour = "#0A0A0A") +
  geom_text(aes(2.5, 2.5, label = "RE"),
            family = "poiret",
            size = 25,
            angle = 180,
            colour = "#FAFAFA") +
  geom_text(aes(3.5, 1.15, label = "INTER"),
            family = "poiret",
            size = 25,
            angle = 90,
            colour = "#FAFAFA") +
  geom_text(aes(2, 0.5, label = "INTER"),
            family = "poiret",
            size = 25,
            angle = 180,
            colour = "#0A0A0A") +
  geom_text(aes(2.5, 1.5, label = "EN"),
            family = "poiret",
            size = 30,
            angle = 270,
            colour = "#FAFAFA")
 
 
#points and "o"s
point_grid <- tibble(
  x = c(1.5, 1.5, 3.5, 3.5),
  y = c(1.5, 3.5, 2.5, 4.5),
  type = c("A", "B", "C", "D")
)
 
 
p4 <- p3 +
  geom_point(data = point_grid,
             aes(x, y, fill = type, colour = type),
             shape = 21,
             stroke = 1.25,
             size = 8,
             show.legend = FALSE) +
  scale_fill_manual(values = c("#0A0A0A", "#FAFAFA", "#AD5B78", "#0A0A0A", "#FAFAFA", "#4A6274")) +
  scale_colour_manual(values = c("#FAFAFA", "#FAFAFA", "#0A0A0A", "#0A0A0A"))
 
 
 
#lines
block_2 <- p4 +
  geom_segment(aes(x = 0.05, xend = 0.95, y = 5.05, yend = 5.05),
               size = 0.6,
               colour = "#FAFAFA") +
  geom_segment(aes(x = 0.05, xend = 0.95, y = 4.95, yend = 4.95),
               size = 0.6,
               colour = "#0A0A0A") +
  geom_segment(aes(x = 1.075, xend = 1.075, y = 0.05, yend = 5.95),
               size = 0.6,
               colour = "#0A0A0A") +
  geom_segment(aes(x = 1, xend = 2.9, y = 3.1, yend = 3.1),
               size = 0.6,
               colour = "#0A0A0A") +
  geom_segment(aes(x = 2.1, xend = 4, y = 2.9, yend = 2.9),
               size = 0.6,
               colour = "#FAFAFA") +
  geom_segment(aes(x = 2.1, xend = 4, y = 5.1, yend = 5.1),
               size = 0.6,
               colour = "#FAFAFA") +
  geom_segment(aes(x = 2.05, xend = 2.05, y = 1.1, yend = 1.9),
               size = 0.6,
               colour = "#FAFAFA") +
  geom_segment(aes(x = 3.95, xend = 3.95, y = 0.1, yend = 4.9),
               size = 0.6,
               colour = "#FAFAFA") +
  geom_segment(aes(x = 2.95, xend = 2.95, y = 4.1, yend = 4.9),
               size = 0.6,
               colour = "#0A0A0A")
 
 
#apply to grid
library(patchwork)
 
 
ggplot() +
  scale_x_continuous(limits = c(0, 10), breaks = c(0:10)) +
  scale_y_continuous(limits = c(0, 10), breaks = c(0:10)) +
  coord_fixed(expand = FALSE, clip = "on") +
  inset_element(block_2, -0.1, 0.9, 0.3, 1.5, clip = TRUE) +
  inset_element(block_1, -0.4, 0.7, 0, 1.3, clip = TRUE) +
  inset_element(block_2, 0.9, 0.9, 1.3, 1.5, clip = TRUE) +
  inset_element(block_1, 1.0, 0.3, 1.4, 0.9, clip = TRUE) +
  inset_element(block_2, 0.8, -0.5, 1.2, 0.1, clip = TRUE) +
  inset_element(block_1, 0.6, 0.7, 1, 1.3, clip = TRUE) +
  inset_element(block_2, 0.3, 0.5, 0.7, 1.1, clip = TRUE) +
  inset_element(block_1, 0, 0.3, 0.4, 0.9, clip = TRUE) +
  inset_element(block_2, 0.7, 0.1, 1.1, 0.7, clip = TRUE) +
  inset_element(block_1, 0.4, -0.1, 0.8, 0.5, clip = TRUE) +
  inset_element(block_2, 0.1, -0.3, 0.5, 0.3, clip = TRUE) +
  inset_element(block_1, -0.2, -0.5, 0.2, 0.1, clip = TRUE) +
  inset_element(block_2, -0.3, 0.1, 0.1, 0.7, clip = TRUE)
 
 
#save
ggsave(here::here("2021", "W52_Self-Discipline", "Prefix.png"), dpi = 200, width = 13.5, height = 13.5, units = "cm")
```

