---
title: "Holy_WEBDuboisChallenge"
author: "Sung Inkyung"
date: '2021 10 5'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidytext)
library(ggpattern)
library(ggforce)
library(colorspace)
library(magick)
library(ggtext)
library(showtext)

font_add_google("IM Fell DW Pica SC")
font_add_google("Saira")
font_add_google("Lato")

```
###Source[tidytuesday by jake kaupp] (https://github.com/jkaupp/tidytuesdays/blob/master/2021/week25/R/analysis.R)
```{r}
bible <- read.csv("C:/Users/inkyscope/Documents/projectR/inkyscroll/data/bible_kjv_new.csv")

words1 <- c("holy", "sanctify", "sanctified", "consecrate", "consecrated", "consecration", "hallow")

df_words1 <- bible %>% 
  select(text) %>% 
  unnest_tokens(word, text) %>% 
  filter(word %in% words1) %>% 
  count(word, sort = T)
  
```


```{r}
cols <- c("#e1d0be", "#fbba00", "#d41735", "#22194e")
text_cols <- c("#d41735", "#22194e", "#fbba00", "#e1d0be")


selected_words <- tibble(
  word = c("hallow", "consecrate", "sanctify", "holy"),
  count = c(15, 37, 132, 611)
) %>% 
  mutate(x0 = 0,
         y0 = c(975, 800, 550, 125),
         fill = cols,
         text_color = text_cols,
         radius = c(59.5, 87.5, 127.5, 249.5))

plot <- ggplot(selected_words, 
               aes(x0 = x0, y0 = y0, r = radius)) +
  geom_circle(aes(fill = fill), 
              size = 0.1) +
  geom_text(aes(x = x0, y = y0, 
                color = text_color, 
                label = count), 
            family = "IM Fell DW Pica SC",
            fontface = "bold", 
            size = 5) +
  geom_text(aes(x = x0, y = y0 - radius, 
                label = word), 
            family = "IM Fell DW Pica SC",
            size = 5, 
            vjust = 1.2) +
  scale_x_continuous(limits = c(-600, 600)) +
  scale_fill_identity() +
  scale_color_identity() +
  coord_equal(clip = "off") +
  labs(title = "HOLY, SANCTIFY, CONSECRATE, HALLOW",
       caption = "**Source**: KJV | **Graphic**: Sung Inkyung") +
  theme_void() +
  theme(plot.background = element_rect(fill = lighten("#ede0d0", 0.7), color = NA),
        plot.title = element_text(size = 16, 
                                  family = "Saira",
                                  hjust = 0.5,
                                  margin = margin(t = 15, b = 25)),
        plot.caption = element_markdown(size = 9,
                                        family = "Lato",
                                        margin = margin(b = 10)))

ggsave("Holy_WEBDuboisChallenge.png", width = 23, height = 25, units = "cm")
```

