---
title: "SHARE"
author: "Sung Inkyung"
date: '2021 12 12'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggforce)
library(ggbump)
library(ggtext)
```


```{r}
df <- tribble(
  ~ Book,  ~n,
  "1 Corinthians 12:23~27", 10,
  "2 Timothy 2:20", 16,
  "Matthew 4:8~9", 32,
  "2 Thessalonians 3:10", 38,
  "Proverbs 18:16", 44,
  "Psalms 41:1", 50,
  "Luke 1:77", 56
) %>% 
  mutate(Book = fct_reorder(Book, n)) 
```


```{r}
plot <- df %>% 
  ggplot(aes(x = as.numeric(Book), y = n)) +
  geom_segment(mapping = aes(x = as.numeric(Book), 
                             xend = as.numeric(Book), 
                             y = 0, yend = 90),
               color = "grey90", 
               linetype = "dotted", 
               size = 0.4) +
  geom_sigmoid(aes(x = as.numeric(Book), 
                   y = -10, 
                   xend = 4, 
                   yend = -90, 
                   group = factor(Book)),
               direction = "y", 
               color = "#1089a2", 
               smooth = 5,
               size = 0.5) + 
  geom_richtext(aes(y = n + 1, 
                    label = Book),
                hjust = 0,
                colour = "#1089a2", 
                size = 4.5, angle = 90,
                fill = "#311432", 
                label.colour = NA) +
  geom_text(label = "ALL WILL SHARE ALIKE\n(1 Samuel 30:24)", 
            aes(x = 3.45, 
                y = -110),
            colour = "#1089a2", 
            face = "bold",
            size = 5,
            hjust = 0.3) +
  lims(x = c(0, 8),
       y = c(-180, 180)) +
  coord_cartesian(clip = 'off') +
  labs(caption= "Graphic: Sung Inkyung") +
  theme_dark() +
  theme(legend.position = "none",
        panel.background = element_rect(fill = "#311432", 
                                        colour = NA),
        plot.background = element_rect(fill = "#311432", 
                                       colour = NA),
        plot.caption = element_text(size = 9,
                                    color = "#99cccc",
                                    margin = margin(b= 10)),
        panel.grid = element_blank(),
        strip.text = element_blank(),
        axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.ticks = element_blank())

ggsave(here::here("2021", "W51_Share", "Share.png"))
```