---
title: "PsalmsPillars"
author: "Sung Inkyung"
date: '2020 5 23'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidytext)
library(ggtext)
library(glue)
library(here)
```


```{r}
Psalms <- readr::read_csv("C:/Users/inkyscope/Documents/projects/data/bible_kjv_new.csv") %>% 
  filter(book == "Psalms") 
```


```{r}
tidy_psalms <- Psalms %>%
  select(chapter, text) %>% 
  unnest_tokens(word, text) %>%
  anti_join(stop_words) %>%
  group_by(word, chapter) %>%
  count(word, sort = TRUE) %>% 
  ungroup() %>% 
  filter(!word %in% c("thou", "thy", "thine", "hast", "art",
                      "shalt", "thee", "hath", "ye", "lord", "god" ))

tidy_psalms %>% 
  count(word, sort = TRUE) %>% 
  filter( n > 40) %>% 
  mutate(word = reorder(word, n)) %>% 
  ggplot(aes(word, n)) +
  geom_col() +
  xlab(NULL) +
  coord_flip() +
  theme_minimal()
```
### Source[tidytuesday by Cedric Sherer] (https://github.com/Z3tt/TidyTuesday/blob/master/R/2020_19_AnimalCrossing.Rmd)
```{r}
Psalms_books <- tidy_psalms %>% 
  mutate(
    chapter = case_when(
      chapter < 42 ~ "1",
      chapter < 73 ~ "2",
      chapter < 90 ~ "3",
      chapter < 107 ~ "4",
      chapter <= 150 ~ "5",
      TRUE ~ as.character(chapter))) %>% 
  inner_join(get_sentiments("afinn"), by = "word") %>% 
  group_by(chapter, word) %>% 
  summarise(
    n = n(),
    contribution = sum(value),
    value = unique(value)
  ) %>% 
  group_by(chapter) %>% 
  mutate(contr_rel = value * n / sum(n)) %>% 
  arrange(chapter, -abs(contribution)) %>% 
  group_by(chapter) %>% 
  slice(1:50) %>% 
  mutate(contribution_praise = if_else(word == "praise", 0, contr_rel)) %>% 
  arrange(-contribution_praise) %>% 
  mutate(rank = row_number()) %>% 
  mutate(line = if_else(word == "praise", rank, NA_integer_)) %>% 
  ungroup() %>% 
  mutate(
    word = str_to_upper(word),
    group = case_when(
      contribution_praise == 0 ~ "praise",
      contribution_praise > 0 ~ "positive",
      contribution_praise < 0 ~ "negative"
    ),
    chapter_lab = glue::glue("Book {chapter}"),
    chapter_lab = fct_reorder(chapter_lab, chapter))
```

```{r}
pal = c(positive = "#006b38ff", negative = "#755139ff", praise = "#f2edd7ff")

plot_wordpillar <- Psalms_books %>% 
  ggplot(aes(chapter, rank,
             label = word,
             color = group,
             size = abs(contr_rel))) +
  geom_richtext(fontface = "bold",
                fill = "#212038",
                label.color = NA,
                label.padding = unit(c(.1, .15, -.1, .05), "lines"),
                label.r = unit(.05, "lines")) +
  scale_x_discrete(expand = c(.06, .06),
                   position = "top",
                   labels = levels(Psalms_books$chapter_lab)) +
  scale_y_continuous(expand =  c(.01, .01)) +
  scale_color_manual(values = pal,
                     guide = F) + 
  scale_radius(range = c(3, 11),
               guide = F) +
  labs(
    x = "",
    y = "",
    title = "Parallel of <span style = 'color: #f2edd7ff'>**PRAISE**</span> Between Positive and Negative Sentiments in Psalms",
    subtitle = "Based on a sentiment analysis of Psalms, top 50 words are filtered from Book 1 to Book 5<br>by contribution value to each book, either in a <span style='color:#006b38ff'>positive</span> or in a <span style='color:#755139ff'>negative</span> way.<br>The size of each word indicates its contribution per book.</span>",
      caption = 'Graphic: Sung Inkyung'
    ) +
  theme_minimal() +
  theme(plot.background = element_rect(fill = "#212038",
                                       color = "#212038"),
        panel.background = element_rect(fill = "#212038",
                                       color = "#212038"),
        plot.title = element_markdown(color = "#c7d3d4ff", 
                                      size = 36,
                                      margin = margin(b = 9)),
        plot.subtitle = element_markdown(color = "#c7d3d4ff", 
                                         size = 28,
                                         lineheight = .9,
                                        margin = margin(b = 20)),
        plot.caption = element_text(color = "#c7d3d4ff",
                                    size = 17, 
                                    margin = margin(t = 20, b = 10)),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text.x.top = element_text(color = "#a2a2a1ff", 
                                         size = 21, 
                                         face = "bold",
                                         margin = margin(b = 10)),
        axis.text.y = element_blank(),
        plot.margin = margin(20, 20, 20, 20))

ggsave(here("2020", "0523_PsalmsPillars", "0523_PsalmsPillars.png"), width = 46, height = 50, units = "cm")
```
