---
title: "WithoutPairs"
author: "Sung Inkyung"
date: '2020 12 15'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidytext)
library(ggtext)
library(tidygraph)
library(ggraph)
library(ggimage)
library(pals)
library(glue)
```


```{r}
bible <- readr::read_csv("C:/Users/inkyscope/Documents/projects/data/bible_kjv_new.csv")
```


```{r}
bigram_stopwords <- c("the", "an", "a", "and", "our", "an", "any", "in", "us", "do", "lest", "at", "that")

bible_bigrams <- bible %>% 
  unnest_tokens(bigram, text, toke = "ngrams", n = 2) %>% 
  select(book, chapter, bigram) %>% 
  separate(bigram, c("word1", "word2"), sep = " ") %>%   
  filter(word1 == "without") %>% 
  filter(!word2 %in% bigram_stopwords) %>% 
  count(book, word2, sort = T) %>% 
  rename(word = word2) %>% 
  mutate(book_word = as.character(glue("{book}_{word}"))) %>% 
  filter(n > 2)

```
### Source[tidytuesday by Kaustav Sen] (https://github.com/kaustavSen/tidytuesday/blob/master/2020/week_50_women_2020.R)

```{r}
nodes <- 
  tibble(node = c("root", unique(bible_bigrams$book), unique(bible_bigrams$book_word))
  ) %>% 
  mutate(levels = case_when(
    node == "root" ~ 1,
    node %in% unique(bible_bigrams$book) ~ 2,
    node %in% unique(bible_bigrams$book_word) ~ 3,
    TRUE ~ 4)) %>% 
  left_join(count(bible_bigrams, book, word, name = "number") %>% 
              mutate(book_word = as.character(glue("{book}_{word}"))), 
            by = c("node" = "book_word")) %>%  
  mutate(book = factor(book, levels = c("Leviticus", "Numbers", "Jeremiah", "Ezekiel", 
                                        "Job", "Psalms", "Proverbs",
                                        "1 Corinthians", "1 Thessalonians")),
         book = fct_rev(book)) %>% 
  arrange(levels, book, word)


edges_level_1 <- bible_bigrams %>% 
  distinct(book) %>% 
  mutate(from = "root") %>% 
  rename(to = book)

edges_level_2 <- 
  bible_bigrams %>%
  distinct(book, book_word) %>% 
  arrange(book, book_word) %>%
  select(from = book, to = book_word)



color_edges <- tibble(
  book = c("Leviticus", "Numbers", "Jeremiah", "Ezekiel", 
           "Job", "Psalms", "Proverbs",  
           "1 Corinthians", "1 Thessalonians"),
  color = as.vector(alphabet(n = 9)))

edges <- 
  bind_rows(edges_level_1, edges_level_2) %>% 
  left_join(color_edges, by = c("to" = "book")) %>% 
  left_join(color_edges, by = c("from" = "book")) %>% 
  mutate(color = coalesce(color.x, color.y)) %>% 
  select(-color.x, -color.y)

graph_data <- tbl_graph(nodes, edges)

image_without <- here::here("2020", "1215", "without.png")
```
 

```{r}
ggraph(graph_data, layout = "partition") +
  geom_edge_diagonal(aes(color = color), alpha = 0.5) +
  geom_node_text(aes(x = x, y = y, label = word, 
                     filter = levels == 3, 
                     color = book), 
                 size = 12,
                 hjust = 1, vjust = 0.5, 
                 lineheight = 0.7) +
  geom_node_text(aes(label = node, 
                     filter = levels == 2, 
                     color = node), 
                 size = 11,
                 vjust = 0.5, fontface = "bold") +
  geom_node_point(aes(filter = levels == 2, color = node), 
                  size = 70, alpha = 0.5) +
  geom_node_point(aes(filter = levels == 2, color = node), 
                  size = 80, shape = 1) +
  geom_node_range(aes(y = y + 0.02, yend = y + 1.5 * number/max(nodes$number, na.rm = TRUE), 
                      x = x, xend = x, filter = levels == 3, 
                      color = book), 
                  size = 12) +
  geom_node_text(aes(x = x, y = y + 1.5 * number/max(nodes$number, na.rm = TRUE), 
                     label = number, filter = levels == 3, 
                     color = book), 
                 nudge_y = 0.025, size = 11,
                 fontface = "bold", 
                 hjust = 0, 
                 vjust = 0.5) +
  geom_image(data = filter(nodes, levels == 1), 
             aes(x = 6, y = 1.2, image = image_without), 
             size = 0.09,
             asp = 1.3) + 
  scale_edge_color_identity() +
  labs(
    title = "Words with **WITHOUT**",
    subtitle = "Illustrated below shows the number of adjacent words of **without** across bible books",
    caption = "**Graphic:** Sung Inkyung") +
  coord_flip() +
   theme(legend.position = "none",
        panel.background = element_rect(fill = "#fffdfa",
                                        color = "transparent"),
        plot.title = element_markdown(size = 60, 
                                      color = "#2A363B", 
                                      hjust = 0.5),
        plot.subtitle = element_markdown(size = 45, 
                                         color = "#2A363B", 
                                         hjust = 0.5),
        plot.caption = element_markdown(size = 30, color = "grey30"),
        plot.margin = margin(10, 10, 10, 10))

ggsave(here::here("2020", "1215", "1215_WithoutPairs.png"), width = 90, height = 80, units = "cm")
  
80
```


