---
title: "job_selected words"
author: "Sung Inkyung"
date: '2021 11 10'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(circlize)
library(tidytext)
```


```{r}
job <- readr::read_csv(here::here("data/bible_kjv_new.csv")) %>% 
    filter(book == "Job") %>% 
    select(-c(book, citation, verse)) %>% 
    filter(chapter %in% 4:37) %>% 
    mutate(
        character = case_when(
            chapter %in% c("6", "7", "9", "10", "12", "13", "14", "16", "17", "19", "21", "23", "24", "26", "27", "28", "29", "30", "31") ~ "Job",
            chapter %in% c("4", "5", "15", "22") ~ "Eliphaz",
            chapter %in% c("8", "18", "25") ~"Bildad",
            chapter %in% c("11", "20") ~ "Zophar",
            chapter %in% c("32", "33", "34", "35", "36", "37") ~"Elihu",
            TRUE ~ as.character(chapter)
        )) %>% 
  unnest_tokens(word, text) %>%
  filter(!is.na(word)) %>% 
  anti_join(stop_words) 

selected_words <- c("prosperity", "almighty", "knowledge", "understanding", "wisdom", "judgement",
                    "iniquity", "words")


df <- job %>% 
  filter(word %in% selected_words)

```


```{r}
df <- df %>% 
  mutate(character = as.factor(character),
         word = as.factor(word))%>%  
  group_by(word, character) %>% 
  count() %>% 
  ungroup()


grid.col <- c(prosperity = "#4000ff",
              almighty = "#8e6883",
              knowledge = "#fbd491", 
              understanding = "#3cd10c",
              wisdom = "#003b4a",
              judgement = "#300f33",
              iniquity = "#bc2734",
              words = "#dad225",
              Job = "#9fb3c7",
              Eliphaz = "#9fb3c7",
              Bildad = "#9fb3c7",
              Zophar = "#9fb3c7",
              Elihu = "#9fb3c7"
                )

chordDiagram(df,
             link.sort = TRUE,
             link.decreasing = TRUE,
             grid.col = grid.col,
             transparency = 0.3,
             annotationTrack = c("name", "grid")
             )

title(main = "Selected Words from Job and his Friends",
      sub = "Source: KJV | Graphic: Sung Inkyung")

circos.clear()

            
#png(filename = "W47_Job_Selected_Words/Job_Selected_Words.png")

```

