---
title: "Bible Books Treemap"
author: "Sung Inkyung"
date: '2020 7 11'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidytext)
library(ggtext)
library(scales)
library(treemapify)
library(showtext)
library(here)

font_add_google("Roboto Condensed", "Roboto Condensed")
showtext_auto()

```


```{r}
bible <- readr::read_csv("C:/Users/inkyscope/Documents/projects/data/bible_kjv_new.csv")

```

```{r}
book_by_characters <- bible %>% 
  group_by(book) %>% 
  summarise(characters = sum(nchar(text))) %>% 
  arrange(desc(characters)) %>% 
  ungroup() %>% 
  mutate(count = scales::comma(characters),
         mark = str_c(book, "\n", count)) 
  
```

```{r}
tree_plot <- book_by_characters %>% 
  ggplot(aes(area = characters,
             label = mark)) +
  geom_treemap(color = "gray90",
               fill = "#131423",
               size = .7) +
  geom_treemap_text(color = "white",
                    place = "topleft",
                    min.size = 0,
                    family = "Roboto Condensed",
                    reflow = T,
                    size = 26) +
  labs(title = "Bible Books by Number of Characters",
       subtitle = "Of the New Testament, Luke, Acts, Matthew are listed in the top 20",
       caption = "**Graphic**: Sung Inkyung") +
  theme(panel.background = element_rect(fill = "white"),
        plot.title = element_text(size = 36,
                                      face = "bold",
                                  margin = margin(b = 5)),
        plot.subtitle = element_text(size = 28,
                                  margin = margin(b = 10)),
        plot.caption = element_markdown(size = 18,
                                    margin = margin(t = 10)),
        plot.margin = margin(20, 20, 20, 20))

ggsave(here("2020", "0711_BibleTreemap", "0711_BibleBooksTreemap.png"), width = 22, height = 14, units = "cm")
```

