---
title: "CharactersWordcloud"
author: "sung inkyung"
date: '2019 8 7'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Source:[tidytuesday by @Z3tt] (https://github.com/Z3tt/TidyTuesday/blob/master/R/2020_19_AnimalCrossing.Rmd)
```{r}
library(tidyverse)
library(tidytext)
library(ggtext)
library(ggwordcloud)
library(cowplot)
library(here)
library(showtext)

font_add_google("Anton")
font_add_google("Lato")
font_add_google("Sarabun")
font_add_google("Lexend Zetta")

showtext_opts(dpi = 320)
showtext_auto(enable = TRUE)

```

```{r}
bible <- readr::read_csv("C:/Users/inkyscope/Documents/projects/data/bible_kjv_new.csv") %>% 
    filter(book == "Job") %>% 
    select(-c(citation, verse)) 
```


```{r}
job <- bible %>%
  filter(book == "Job") %>%
  filter(!chapter %in% c("1", "2", "3")) %>% 
  mutate(
    chapter = case_when(
    chapter %in% c("6", "7", "9", "10", "12", "13", "14", "16", "17", "19", "21", "23", "24", "26", "27", "28", "29", "30", "31", "40", "41") ~ "Job",
    chapter %in% c("38", "39", "42") ~ "God",
    TRUE ~ "Friends"
    )) 

job_tf_idf <- job %>%
  unnest_tokens(word, text) %>%
  anti_join(stop_words) %>%
  group_by(word, character = chapter) %>%
  count(sort = TRUE) %>% 
  ungroup() %>% 
  filter(!word %in% c("thou", "thy", "thine", "hast", "art",
                      "shalt", "thee", "hath", "ye", "yea", "thereof", "canst", "ha")) %>% 
  bind_tf_idf(word, character, n) %>% 
  arrange(desc(tf_idf)) 

```


```{r}
plot <- job_tf_idf %>% 
  mutate(word = factor(word, levels = rev(unique(word)))) %>% 
  group_by(character) %>% 
  top_n(6, tf_idf) %>% 
  ungroup() %>% 
  ggplot(aes(word, tf_idf, fill = character))+
  geom_col(stat = "identity",
           alpha = .7,
           show.legend = FALSE) +
  labs(x = NULL,
       y = "tf_idf") +
  scale_x_discrete(expand = c(0, 0)) +
  scale_fill_brewer(palette = "Dark2") +
  facet_wrap(~ character, scales = "free")+
  coord_flip() +
   theme_minimal()
```

```{r}
## ggplot theme
theme_set(theme_minimal())
theme_update(axis.text = element_blank(),
             axis.title = element_blank(),
             axis.ticks = element_blank(),
             panel.grid = element_blank(),
             strip.text = element_text(color = "grey60",
                                       family = "Lexend Zetta"),
             plot.background = element_rect(fill = "grey7", 
                                            color = "grey7"),
             plot.margin = margin(20, 60, 10, 20),
             plot.title = element_text(color = "grey75",
                                       family = "Anton",
                                        size = 18, 
                                       hjust = .5, 
                                       margin = margin(b = 7)),
             plot.subtitle = element_text(color = "grey55", 
                                          family = "Lato",
                                          size = 12,
                                          hjust = .5, 
                                          margin = margin(b = 15)),
             plot.caption = element_text(color = "grey55", 
                                         size = 7, 
                                         face = "bold",
                                         hjust = 1.1, 
                                         margin = margin(t= 15)))
```

```{r}
job_afinn <- job_tf_idf %>% 
  filter(!word %in% c("ass", "suck"))%>%
  inner_join(get_sentiments("afinn"), by = "word") %>% 
  mutate(level = case_when(
    character == "Friends" ~ 0,
    character == "Job" ~ 1,
    character == "God" ~ 2
  )) %>% 
  group_by(word, level) %>% 
  summarise(contribution = n*value) %>% 
  mutate(group = if_else(contribution > 0, "A", "B")) %>% 
  mutate(group = if_else(word == "god", "C", group)) %>% 
  arrange(level, -abs(contribution)) %>% 
  group_by(level) %>% 
  slice(1:40) %>% 
  ungroup() 

job_afinn %>% 
  filter(word == "god")
```

```{r}
wordcloud_level <- function(l) {
  p <-
    job_afinn %>% 
    filter(level == l) %>%
    arrange(-contribution) %>% 
    ggplot(aes(label = word, 
               size = contribution, 
               color = group)) +
    geom_text_wordcloud(eccentricity = 1,
                        family = "Sarabun",
                        seed = 2020) +
    scale_x_continuous(expand = c(0, 0)) +
    scale_y_continuous(expand = c(0, 0)) +
    scale_color_manual(values = c("#3ed7de", "#834800", "white"),
                       guide = "none") +
    scale_size_area(max_size = 10) +
    theme(plot.background = element_rect(color = NA,
                                         fill = NA),
          panel.background = element_rect(color = NA,
                                        fill = NA))
}

base <- 
  tibble(
    x = c(.2, .54, .85),
    y = rep(.05, 3),
    label = c("Friends", "Job", "God")) %>% 
  ggplot(aes(x, y, label = label)) +
  geom_text(color = "gray75",
            family = "Lexend Zetta",
            size = 7) +
  scale_x_continuous(expand = c(0, 0),
                     limits = c(0, 1)) +
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0, 1)) +
  labs(title = str_to_upper("Which Word Means More to You?"),
       subtitle = "Illustrated below shows how important the word is to each person\nby applying the AFINN sentiment value to the words selected by TF-IDF. ",
       caption = "Source: King James Bible | Graphic: Sung Inkyung")

p <- ggdraw(base) +
  draw_plot(wordcloud_level(0), .23, .54, .55, .85, hjust = .5, vjust = .5) +
  draw_plot(wordcloud_level(1), .54, .54, .43, .85, hjust = .5, vjust = .5) +
  draw_plot(wordcloud_level(2), .82, .54, .5, .85, hjust = .5, vjust = .5)

ggsave("0807_CharactersWordcloud.png", width = 26, height = 15, units = "cm")
  
```

