---
title: "Hebrews"
author: "Sung Inkyung"
date: '2020 2 28'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidytext)
library(ggtext)
library(here)
library(showtext)

font_add_google("Staatliches")
font_add_google("Lato")
font_add_google("Saira")
```


```{r}
Hebrews <- readr::read_csv("C:/Users/inkyscope/Documents/projects/data/bible_kjv_new.csv") %>% 
  filter(book == "Hebrews")

characters <- Hebrews %>% 
  summarize(characters = sum(nchar(text))) %>% 
  arrange(desc(characters))

library(wordcloud)

Hebrews %>% 
  unnest_tokens(word, text) %>% 
  anti_join(stop_words) %>% 
  count(word) %>% 
  with(wordcloud(word, n, max.words = 100))

library(reshape2)

Hebrews %>% 
  unnest_tokens(word, text) %>% 
  anti_join(stop_words) %>% 
  inner_join(get_sentiments("bing")) %>% 
  count(word, sentiment, sort = TRUE) %>% 
  acast(word ~ sentiment, value.var = "n", fill = 0) %>% 
  comparison.cloud(colors = c("gray20", "gray80"),
                   max.words = 100)
```


```{r}
frequency <- Hebrews %>% 
  unnest_tokens(word, text) %>% 
  anti_join(stop_words) %>% 
  filter(!str_detect(word, "[0-9]"),
         !str_detect(word, "ye|thou|saith|thy|thee|thee|hath|god|lord|dai")) %>% 
  count(word, sort = TRUE)

  frequency %>% 
    filter(n >= 10) %>% 
    mutate(word = fct_reorder(word, n)) %>% 
    ggplot(aes(word, n)) +
    geom_col()+
    coord_flip()
    
```

```{r}
new_word <- Hebrews %>% 
  unnest_tokens(word, text) %>% 
  anti_join(stop_words) %>% 
  filter(!str_detect(word, "[0-9]"),
         !str_detect(word, "ye|thou|saith|thy|thee|thee|hath|god|lord|dai")) %>% 
  mutate(rank = row_number(),
         n = 1) %>% 
  select(chapter, word, rank, n)

View(new_word)

```


```{r}
top_picks <- new_word %>% 
  group_by(chapter, word) %>% 
  mutate(popularity = 1988 - rank) %>% 
  tally(popularity) %>% 
  top_n(1) %>% 
  mutate(top_1 = TRUE) %>% 
  ungroup() %>% 
  select(word, top_1)


word <- new_word %>% 
  left_join(top_picks, by = "word") %>% 
   mutate(top_1 = case_when(
    is.na(chapter|top_1) ~ 1,
    TRUE ~ 0
  )) %>% 
  arrange(desc(rank))


View(word)

chapter_order <- new_word %>% 
  group_by(chapter) %>% 
  tally()

```

```{r}
word_plot <- word %>% 
  mutate(chapter = factor(chapter)) %>% 
  ggplot(aes(fct_relevel(chapter, "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13"), 
             y = n,
             label = word, color = top_1)) +
  geom_text(position = "stack", 
            stat = "identity",
            size = 5,
            family = "Lato",
            show.legend = FALSE,
            color = "#cccc00" ) +
  annotate("text", x = 1, y = 106, label = "angels", color = "#cd1076", family = "Saira", size = 5.5) +
  annotate("text", x = 2, y = 130, label = "angels", color = "#cd1076", family = "Saira", size = 5.5) +
  annotate("text", x = 3, y = 114, label = "house", color = "#cd1076", family = "Saira", size = 5.5) + 
  annotate("text", x = 4, y = 110, label = "rest", color = "#cd1076", family = "Saira", size = 5.5) +
  annotate("text", x = 5, y = 85, label = "priest", color = "#cd1076", family = "Saira", size = 5.5) +
  annotate("text", x = 6, y = 132, label = "promise", color = "#cd1076", family = "Saira", size = 5.5) +
  annotate("text", x = 7, y = 186, label = "priest", color = "#cd1076", family = "Saira", size = 5.5) +
  annotate("text", x = 8, y = 89, label = "covenant", color = "#cd1076", family = "Saira", size = 5.5) +
  annotate("text", x = 9, y = 202, label = "blood", color = "#cd1076", family = "Saira", size = 5.5) +
  annotate("text", x = 10, y = 222, label = "offering", color = "#cd1076", family = "Saira", size = 5.5) +
  annotate("text", x = 11, y = 317, label = "faith", color = "#cd1076", family = "Saira", size = 5.5) +
  annotate("text", x = 12, y = 219, label = "set", color = "#cd1076", family = "Saira", size = 5.5) +
  annotate("text", x = 13, y = 145, label = "remember", color = "#cd1076", family = "Saira", size = 5.5) +
  labs(x = " ",
       y = " ",
       title = "Top Picks from the Book of Hebrews",
       subtitle = "Illustrated below shows the most frequent words by chapter in the book of Hebrews.<br>Inspired by **MY World** by ToughTalk Jazz band released in April 28, 2020",
       caption = "Source: King James Bible | Graphic: Sung Inkyung") +
  theme_minimal() +
  theme(legend.position = "none",
        plot.title = element_text(size = 24,
                                  family = "Staatliches",
                                  margin = margin(t =35,
                                                  b = 9)),
        plot.subtitle = element_markdown(size = 17,
                                        family = "Lato",
                                        lineheight = 1.1,
                                        margin = margin(b = 15)),
        plot.caption = element_text(size = 12,
                                    family = "Saira"),
        panel.grid = element_blank(),
        axis.text.x = element_text(size = 15,
                                   family = "Saira",
                                   face = "bold"),
        axis.text.y = element_blank(),
        plot.margin = margin(10, 10, 10, 10))
  
ggsave("0228_HebrewsTopPicks.png", width = 35, height = 25, units = "cm")
```

