---
title: "BibleBooksTree"
author: "Sung Inkyung"
date: '2020 11 18'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidytext)
library(ggtext)
library(scales)
library(ggraph)
library(ggforce)
library(paletteer)
library(colorspace)
library(MetBrewer)
library(glue)
library(showtext)

font_add_google("Ranchers")
font_add_google("Caveat")
font_add_google("Caveat Brush")

showtext_opts(dpi = 320)
showtext_auto()
```


```{r}
bible <- readr::read_csv("C:/Users/inkyscope/Documents/projects/data/bible_kjv_new.csv")

bible_word <- bible %>% 
  unnest_tokens(word, text) %>% 
  anti_join(stop_words) %>% 
  group_by(book) %>% 
  summarise(n = n()) %>% 
  arrange(-n) %>% 
  ungroup() 
```


```{r}
pos <- pack_circles(bible_word$n) %>% 
  as_tibble()

layout <- tibble(x = pos$V1,
                 y = pos$V2,
                 r = sqrt(bible_word$n/pi))

plot_data <- bind_cols(bible_word, layout) %>% 
  mutate(n = scales::comma(round(n), accuracy = 1))

top <- plot_data %>% 
  slice_max(n = 12, order_by = n)

```

```{r}
trunk <- tibble(x = c(-25, -25, -50, 50, 24, 25),
                y = c(-200, -350, -400, -400, -350, -200))

```

```{r}
tree_word <- plot_data %>% 
  ggplot() +
  geom_shape(data = trunk, aes(x = x + 0.05, y = y), 
             fill = "#765c48", 
             color = darken("#765c48")) +
  geom_circle(aes(x0 = x, y0 = y, r = r, 
                  fill = book, color = book), 
              show.legend = FALSE, 
              inherit.aes = FALSE) +
  geom_text(data = top, 
            aes(x = x, y = y, 
                label = glue("{str_wrap(book, 10)}\n{n}")), 
            color = "#ebe4dc",
            family = "Caveat Brush",
            size = 4.5,
            lineheight = 0.9) +
  scale_fill_manual(values = met.brewer("Renoir", n = 66)) +
  scale_color_manual(values = met.brewer("Morgenstern", n = 66)) +
  coord_equal() +
  labs(x = NULL,
       y = NULL,
       title = "Bible Books",
       subtitle = "Top 12 books are displayed by number of words",
       caption = "**Source**: King James Bible | **Graphic**: Sung Inkyung") +
  theme_minimal() +
  theme(panel.grid = element_blank(),
        plot.title = element_text(family = "Ranchers",
                                  size = 36, 
                                  hjust = .5,
                                  margin = margin(t = 20, b = 9)),
        plot.subtitle = element_text(family = "Caveat",
                                     size = 30,
                                     hjust = .5,
                                     margin = margin(b = 20)),
        plot.caption = element_markdown(family = "Caveat",
                                        size = 14,
                                        hjust = .5,
                                        margin = margin(t = 30, b = 20)),
        axis.text = element_blank())

ggsave("1118_BibleBooksTree.png", width = 25, height = 25, units = "cm")
  
```
