---
title: "Ezekiel"
author: "Sung Inkyung"
date: '2020 11 15'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggtext)
```


```{r}
bible <- readr::read_csv("C:/Users/inkyscope/Documents/projects/data/bible_kjv_new.csv") 
```


```{r}
ezekiel_lord <- bible %>% 
  select(book, chapter, verse, text) %>% 
  filter(book == "Ezekiel") %>% 
  mutate(lord = str_count(text, pattern = "LORD")) %>% 
  group_by(chapter, verse) %>% 
  summarise(count = sum(lord)) %>% 
  ungroup() %>% 
  mutate(id = row_number())


chapter_lord <- ezekiel_lord %>% 
  group_by(chapter) %>% 
  mutate(total = sum(count)) %>% 
  ungroup() %>% 
  distinct(chapter, total)
```


```{r}
plot_lord <- ezekiel_lord %>% 
  ggplot(aes(x = verse, y = -chapter)) +
  geom_point(aes(size = count, 
                 color = factor(count)),
             show.legend = F) +
  geom_point(data = chapter_lord,
             aes(x = 64, y = -chapter,
                 fill = total),
             shape = 21,
             size = 8, 
             stroke = .7, 
             color = "#ffffff",
             show.legend = F) +
  geom_text(data = chapter_lord,
            aes(x = 64, y = -chapter, label = total),
            color = "gray20",
            size = 3.5, 
            show.legend = F) +
  scale_x_continuous(limits = c(1, 64),
                     expand = c(.01, 0)) +
  scale_y_continuous(breaks = seq(-48, -1),
                     labels = seq(48, 1, -1),
                     expand = c(.01, 0)) +
  scale_color_manual(values = c("#93385FFF", "#9F6B99FF", "#4F3466FF", "#301728FF"),
                     name = "count") + #purple, lilac, petunia, aubergine gleam
  scale_fill_gradient(low = "#FFF3EB", high = "#FFB885") +
  labs(x = " ",
       y = " ", 
       title = "The Number of Times of <span style ='color:#4a2b47'>**LORD**</span> occurred through 48 Chapters in the Book of Ezekiel",
       subtitle = "God tells us over and over that he is the LORD.\nThis revelation of his self-identification is a constant echo by a prophet Ezekiel.",
       caption = "**Graphic**: Sung Inkyung") +
  theme(plot.background = element_rect(fill = "#f5f6f4"),
        panel.background = element_rect(fill = "#f5f6f4"),
        panel.grid = element_blank(),
        plot.title = element_markdown(size = 24,
                                      margin = margin(t = 20, b = 10)),
        plot.subtitle = element_text(size = 20,
                                     margin = margin(b = 20)),
        plot.caption = element_markdown(size = 14,
                                        margin = margin(t = 30, b= 20, r = 20)),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_text(size = 14))


ggsave(here::here("2020", "1115_Ezekiel", "1115_Ezekiel_Lord.png"), width = 46, height = 40, units = "cm")
```



