---
title: "Bible Books"
author: "Sung Inkyung"
date: '2019 11 5'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidytext)
library(scales)
library(paletteer)
library(patchwork)
library(showtext)

font_add_google("Anton")
font_add_google("Fira Sans Condensed")
font_add_google("Jost")

showtext_opts(dpi = 320)
showtext_auto(enable = TRUE)
```


```{r}
bible <- readr::read_csv("C:/Users/inkyscope/Documents/projects/data/bible_kjv_new.csv") %>% 
  mutate(Testament = ifelse(book %in% c("Matthew", "Mark", "Luke",
                                        "John", "Acts", "Romans", 
                                        "1 Corinthians", 
                                        "2 Corinthians",  "Galatians",
                                        "Ephesians", "Philippians",
                                        "Colossians", 
                                        "1 Thessalonians",
                                        "2 Thessalonians", 
                                        "1 Timothy", "2 Timothy",
                                        "Titus","Philemon",
                                        "Hebrews", "James", "1 Peter",
                                        "2 Peter", "1 John", "2 John",
                                        "3 John","Jude", "Revelation"), "New Testament", "Old Testament"))
```

### source[Joshua Feldman](https://github.com/joshua-feldman/King-James-Bible/blob/master/Bible.R)
```{r}
book_by_characters <- bible %>% 
  group_by(book, Testament) %>% 
  summarize(characters = sum(nchar(text))) %>% 
  arrange(desc(characters))

book_by_characters$book <- factor(book_by_characters$book, 
                                  levels = book_by_characters $book[order(book_by_characters$characters)]) #reorder books according to length
book_by_characters$Testament <- factor(book_by_characters$Testament,
                                       levels = c("Old Testament", "New Testament"))

book_by_characters %>% 
  ggplot(aes(book, characters, fill = Testament)) +
  geom_col() +
  coord_flip()+
  scale_fill_manual(values = c("Old Testament" = "#112358",
                               "New Testament" = "#dd2a7b")) +
  scale_y_continuous(expand = c(0, 0),
                     label = comma) +
  labs(x = "",
       y = "# of characters per book",
       title = "Books of the King James Bible by word frequency") +
  theme_minimal()

book_by_characters %>% 
  ggplot(aes(book, characters, fill = Testament)) +
  geom_col(show.legend = FALSE) +
  scale_fill_manual(values = c("Old Testament" = "#112358",
                               "New Testament" = "#dd2a7b")) +
  scale_y_continuous(expand = c(0, 0),
                     label = comma) +
  coord_flip() +
  facet_wrap(~Testament, scales = "free_y") +
  labs(x = "",
       y = "# of characters per book",
       title = "Books of the King James Bible by character frequency") +
  theme_minimal()
```


```{r}
old_length_words <- sum(nchar(bible$text[bible$Testament == "Old Testament"]))
new_length_words <- sum(nchar(bible$text[bible$Testament == "New Testament"]))
```


```{r Analysis book by words}
book_by_words <- bible %>% 
  unnest_tokens(word, text) %>% 
  count(book, Testament, word, sort = TRUE) %>% 
  ungroup() %>% 
  group_by(book, Testament) %>% 
  summarise(count = sum(n)) %>% 
  arrange(desc(count))

book_by_words$book <- factor(book_by_words$book,
                             levels = book_by_words$book[order(book_by_words$count)]) # Reorder books according to length
book_by_words$Testament <- factor(book_by_words$Testament, 
                                  levels = c("Old Testament", "New Testament"))

p1 <- book_by_words %>% 
  ggplot(aes(count, book, fill = Testament)) +
  geom_col(show.legend = FALSE)+
  scale_fill_manual(values = c("Old Testament" = "#112358",
                               "New Testament" = "#dd2a7b")) +
  scale_x_continuous(breaks = seq(0, 40000, 20000),
                     expand = c(0, 0),
                     label = comma) +
  labs(x = "",
       y = "# of words per testament") +
  theme_minimal() +
  theme(plot.backgroun = element_rect(fill = "black",
                                      color = NA),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text = element_text(size = 9,
                                 family = "Fira Sans Condensed",
                                 color = "#d2d2cf"),
        plot.margin = margin(10, 10, 10, 10))


p2 <- book_by_words %>% 
  ggplot(aes(count, book, fill = Testament)) +
  geom_col(show.legend = FALSE) +
  scale_fill_manual(values = c("Old Testament" = "#112358",
                               "New Testament" = "#dd2a7b")) +
  scale_x_continuous(breaks = seq(0, 40000, 20000),
                     expand = c(0, 0),
                     label = comma) +
  facet_wrap(~Testament, scales = "free_y") +
  labs(x = "",
       y = "# of words per testament") +
  theme_minimal() +
  theme(plot.backgroun = element_rect(fill = "black",
                                      color = NA),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text = element_text(size = 9,
                                 family = "Fira Sans Condensed",
                                 color = "#d2d2cf"),
        plot.margin = margin(10, 10, 10, 10))


patchwork <- p1 + p2

plot_final <- patchwork + plot_annotation(
  title = "Books of the King James Bible by Word Frequency",
  caption = "Graphic: Sung Inkyung") &
  theme(legend.position="none",
        plot.backgroun = element_rect(fill = "black",
                                      color = NA),
        panel.backgroun = element_rect(fill = "black",
                                      color = NA),
        plot.title = element_text(size = 26,
                                  family = "Anton",
                                  color = "#e2e5de",
                                  hjust = 0.5,
                                  margin = margin(t = 10, b= 15)),
        plot.caption = element_text(size = 11,
                                    family = "Jost",
                                    color = "#808080",
                                    hjust = 1,
                                    margin = margin(t = 20)),
        panel.grid = element_blank(),
        plot.margin = margin(10, 10, 10, 10))
  


ggsave("1105_BibleBooks.png", width = 25, height = 25, units = "cm")
```
