---
title: "PsalmsEmotionsDendrogram"
author: "Sung Inkyung"
date: '2020.3.7'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Source[tidytuesday by Jake kaupp](https://github.com/jkaupp/tidytuesdays/blob/master/2020/week3/R/analysis.R)
```{r}
library(tidyverse)
library(tidytext)
library(ggtext)
library(ggraph)
library(tidygraph)
library(paletteer)
library(here)
library(showtext)

font_add_google("Orbitron")
font_add_google("Saira")
font_add_google("Saira Condensed")
font_add_google("IBM Plex Sans")

showtext_opts(dpi = 320)
showtext_auto()
```

```{r}
bible <- readr::read_csv("C:/Users/inkyscope/Documents/projects/data/bible_kjv_new.csv") %>% 
  filter(book == "Psalms")
```

```{r}
psalms_stop_word <- c(c("thy", "thou", "thine", "thee", "hast", "hath", "lord", "god", "ye", "yea")) 

psalms <- bible %>% 
  select(-c("citation", "book", "verse")) %>% 
  unnest_tokens(word, text) %>% 
  anti_join(stop_words) %>% 
  filter(!word %in% psalms_stop_word,
         str_detect(word, "[a-z]"))
psalms_nrc <- psalms %>% 
  inner_join(get_sentiments("nrc")) %>% 
  filter(!is.na(sentiment)) %>% 
  mutate(sentiment = factor(sentiment)) %>% 
  count(word, sentiment, sort = TRUE) %>% 
  filter(n > 7) 
```


```{r}
root <- tibble(to = unique(psalms_nrc $sentiment),
               from = "origin")

groups <- distinct(psalms_nrc , word, sentiment) %>% 
  set_names(c("to", "from"))

order <- groups %>% 
  count(from) %>% 
  pull(from) %>% 
  c(., NA)

edges <- bind_rows(root, groups)


nodes <- tibble(name = unique(c(edges$from, edges$to))) %>% 
  mutate(group = edges$from[match(name, edges$to)]) %>% 
  mutate(group = ifelse(group == "origin", NA, group))

graph <- tbl_graph(edges = edges, nodes = nodes, directed = TRUE)

stem_labels <- create_layout(graph, layout = 'dendrogram', circular = TRUE) %>% 
  filter(leaf == FALSE) %>% 
  mutate(group = name,
         n = count(groups, from) %>% pull(n) %>% c(NA_real_, .)) %>% 
  slice(-1) %>% 
  mutate(percent = n/sum(n, na.rm = TRUE)) %>% 
  mutate(label = str_remove(name, "simple-")) %>%
  mutate(label = str_to_upper(str_replace_all(label, "(?<=.)(?!$)", " ")))

```

```{r}
big_plot <- ggraph(graph, layout = 'dendrogram', circular = TRUE) + 
  geom_edge_diagonal(colour  = "grey", alpha = 0.1) +
  geom_node_text(aes(x = x*1.3, y = y*1.3, filter = leaf, label = name,  
                     colour = group, 
                     angle = -((-node_angle(x, y)+90) %% 180) + 90,  
                     hjust = ifelse(between(node_angle(x,y), 90, 270), 0, 1)), 
                 family = "IBM Plex Sans",
                 size = 2.2) +
  geom_node_text(aes(x = x*2.7, y = y*2.7, 
                     label = label, 
                     color = group, 
                     hjust = ifelse(between(node_angle(x,y), 90, 270), 1, 0)), 
                 family = "Saira",
                 size = 4.5, 
                 data = stem_labels)  +
  geom_node_text(aes(x = x*2.1, y = y*2.1, 
                     label = scales::percent(percent), 
                     color = group, 
                     hjust = ifelse(between(node_angle(x,y), 90, 270), 1, 0)), 
                 family = "Saira Condensed",
                 size = 3,  data = stem_labels)  +
  geom_node_point(aes(filter = leaf, colour = group, alpha = 0.2)) +
  annotate("text", x = 0, y = 0, 
           label = "P S A L M S\nSENTIMENTS", family = "Orbitron", size = 7, color = "white") +
  scale_colour_paletteer_d("yarrr::basel") + 
  labs(x = NULL, 
       y = NULL,
       title = "Classification and Distribution of Psalms Sentiments",
       subtitle = "371 words from Psalms book are classified by NRC lexicon.\nPositive sentiments(joy, trust, surprise, anticipation): 41%.\nNegative sentiments(fear, sadness, anger, disgust): 59%.", 
       caption = "**Graphic**: Sung Inkyung") +
  expand_limits(x = c(-1.7, 1.5), y = c(-1.7, 1.5)) +
  coord_equal() +
  theme(legend.position="none",
        axis.text = element_blank(),
        panel.background = element_rect(fill = "black"),
        plot.title = element_text(family = "Saira",
                                  size = 24,
                                  face = "bold",
                                  margin = margin(b = 7)),
        plot.subtitle = element_text(family = "IBM Plex Sans",
                                     size = 20,
                                     lineheight = 1.1,
                                     margin = margin(b = 10)),
        plot.caption = element_markdown(family = "Saira Condensed",
                                        size = 11),
        plot.margin = margin(10, 10, 10, 10)) 
  

ggsave("PsalmsEmotionsDendrogram.png", width = 30, height = 30, units= "cm")

```

