---
title: "TF-IDF Net"
author: "Sung Inkyung"
date: '2021 1 30'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Source[tidytuesday by oggismetto] (https://github.com/oggismetto/tidytuesday/blob/master/code/2020_22_Cocktails.Rmd)
```{r}
library(tidyverse)
library(tidytext)
library(ggtext)
library(igraph)
library(ggraph)
library(widyr)
library(showtext)

font_add_google("Source Sans Pro")
font_add_google("Rambla")


showtext_opts(dpi = 320)
showtext_auto(enable = TRUE)

```


```{r}
bible <- readr::read_csv("C:/Users/inkyscope/Documents/projects/data/bible_kjv_new.csv") %>% 
  mutate(testament = ifelse(book %in% c("Matthew", "Mark", "Luke",
                                        "John", "Acts", "Romans", 
                                        "1 Corinthians", 
                                        "2 Corinthians",  "Galatians",
                                        "Ephesians", "Philippians",
                                        "Colossians", 
                                        "1 Thessalonians",
                                        "2 Thessalonians", 
                                        "1 Timothy", "2 Timothy",
                                        "Titus","Philemon",
                                        "Hebrews", "James", "1 Peter",
                                        "2 Peter", "1 John", "2 John",
                                        "3 John","Jude", "Revelation"), "New Testament", "Old Testament"))
```


```{r}
bible_stop_words <- c(c("art", "thy", "thou", "thine", "thee", "hast", "hath","shalt",
                         "ye", "yea", "saith", "thereof", "wherefore", "lo", "aaron", "aaron's", "aaronites", "abarim")) 

df <- bible %>% 
  filter(testament == "New Testament") %>% 
  select(book, text) %>% 
  unnest_tokens(word, text) %>% 
  filter(!word %in% bible_stop_words) %>% 
  anti_join(stop_words, by = "word") %>% 
  count(book, word, sort = T) %>% 
  bind_tf_idf(word, book, n) %>% 
  slice_max(n = 1000, order_by= tf_idf)

new_node_edges <- df %>% 
  distinct(book, word) %>% 
  pairwise_cor(book, word, sort = T) %>% 
  filter(correlation > 0) 

```

```{r}
# New testament nodes

new_node_size <- df %>% 
  distinct(book, word) %>% 
  count(book, sort = T)

new_node_color <- df %>% 
  distinct(book, word) %>% 
  group_by(book) %>% 
  filter(word %in% c("joy", "faith", "gentle",  "patient", "humble", "true", "right", "holy", "pure", "love", "kind")) %>% 
  filter(row_number() == 1)


new_node_attributes <- new_node_size %>% 
  inner_join(new_node_color) %>% 
  merge(new_node_edges, 
        by.x = "book",
        by.y = "item1",
        all.y = T) %>% 
  distinct(book, n, word) %>% 
  rename(top_word = word) 
```


```{r}
# network
net <- graph_from_data_frame(d = new_node_edges,
                             vertices = new_node_attributes,
                             directed = F)
lay <- create_layout(net, layout = "kk")

```

```{r}
# plot

plot_new <- lay %>% 
  ggraph() +
  geom_edge_link(aes(edge_color = correlation),
                 edge_width = 1) +
  geom_node_point(aes(fill = top_word, size = n),
                  colour = "white",
                  pch = 21, 
                  size = 4.5) +
  geom_node_text(aes(label = name),
                 family = "Rambla",
                 size = 3.5,
                 repel = T) +
  scale_edge_color_distiller(palette = "PuRd", direction = 1) +
  scale_fill_manual(values = c("#0f4256", "#eb1eb5", "#c5d2d3"),
                    labels = c("humble", "pure", "not detected")) +
  labs(title = "Be <span style = 'color:#0f4256'>**Humble**</span> and <span style = 'color: #eb1eb5'>**Pure**</span>",
       subtitle = "Illustrated below shows the correlation between the New Testament Books containing words selected by tf-idf values\nSelected words : joy, faith, gentle, patient, humble, true, right, holy, pure, love, kind",
       caption = "Source: KJV | Graphic: Sung Inkyung",
       fill = "Words",
       edge_color = "Correlation") +
  theme_void() +
  theme(plot.background = element_rect(fill = "#c5d2d3", 
                                       color = NA),
        legend.title = element_text(size = 9),
        legend.text = element_text(size = 9),
        plot.title = element_markdown(size = 20,
                                      family = "Source Sans Pro",
                                      margin = margin(b = 7)),
        plot.subtitle = element_text(size = 12,
                                     family = "Source Sans Pro",
                                     lineheight = 0.9,
                                     margin = margin(b = 15)),
        plot.caption = element_text(size = 10,
                                    family = "Source Sans Pro",
                                    color = "gray45",
                                    hjust = 1.2,
                                    margin = margin(t = 20)),
        panel.grid = element_blank(),
        plot.margin = margin(20, 20, 20, 10))

ggsave("WordNet.png", dpi = 320, width = 22, height = 15, units = "cm")

```
