---
title: "GospelsPolygon"
author: "Sung Inkyung"
date: '2020 3 15'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidytext)
library(ggtext)
library(patchwork)
library(here)
library(showtext)

font_add_google("Staatliches")
font_add_google("Comfortaa")
font_add_google("Fira Sans Condensed")

showtext_opts(dpi = 320)
showtext_auto(enable = TRUE)

```
### Source[tidytuesday by jake lawlor] (https://github.com/jakelawlor/TidyTuesday_JL/blob/master/CodeFiles/Jan21.20.Spotify.Rmd)

```{r}
bible <- readr::read_csv("C:/Users/inkyscope/Documents/projects/data/bible_kjv_new.csv") %>% 
  filter(book %in% c("Matthew", "Mark", "Luke", "John")) %>% 
  select(book, text)

gospels <- bible %>% 
  unnest_tokens(word, text) %>% 
  anti_join(stop_words) %>% 
  filter(!str_detect(word, "[0-9]"),
         !str_detect(word, "ye|thou|saith|thy|thee|thee|hath|god|lord|dai|jesus|son|father")) 
```


```{r}
gospels_stop_word <- c(c("thy", "art", "john", "thou", "thine", "thee", "hast", "hath", "lord", "god", "ye", "yea"))

gospels_nrc <- gospels %>% 
  inner_join(get_sentiments("nrc")) %>% 
  anti_join(stop_words) %>% 
  filter(!word %in% gospels_stop_word,
         str_detect(word, "[a-z]")) %>% 
  group_by(book, word, sentiment) %>% 
  summarize(value = n()) %>% 
  filter(value > 10) %>% 
  ungroup()

gospels_nrc %>% 
  count(sentiment, sort = TRUE)
```


```{r}
order <- c("positive",
           "joy",
           "anticipation",
           "trust",
           "surprise",
           "negative",
           "sadness",
           "anger",
           "fear",
           "disgust")
```
  
  
```{r}
main <- gospels_nrc %>% 
  ggplot(aes(x = sentiment, y = value, 
             group = book,
             fill = book, color = book)) +
  geom_polygon(aes(group = word),
               alpha = .01, size = .2, fill = NA,
               show.legend = F) +
  geom_polygon(aes(x = sentiment, y = value, 
                   group = book, 
                   color = book, 
                   fill = book),
               alpha =.4,
               size = .7, 
               show.legend = F) +
  scale_x_discrete(limits = order,
                   labels = c("Positive", "Joy", "Anticipation",
                              "Trust", "Surprise", "Negative",
                             "Sadness", "Anger", "Fear", "Disgust")) +
  scale_color_manual(values = c("#eea990", "#854442", "#d73232", "#00b3ff" ),
                     labels = c("Matthew", "Mark", "Luke", "John")) + 
  scale_fill_manual(values = c("#eea990", "#854442", "#d73232", "#00b3ff" )) +
  coord_polar(clip = "off") +
  labs(title = "<span style = 'color:#eea990'>**Matthew**</span> <span style = 'color:#854442'>**Mark**</span> <span style = 'color:#d73232'>**Luke**</span>
       <span style = 'color:#00b3ff'>**John**</span>") +
  ylim(0, 40) +
  theme_minimal() +
  theme(axis.title = element_blank(),
        axis.ticks = element_blank(),
        axis.text.x = element_text(size = 14,
                                   family = "Comfortaa"),
        axis.text.y = element_blank(),
        plot.title = element_markdown(size = 36,
                                      family = "Staatliches",
                                      hjust = .5,
                                      margin = margin(b = 20)))

```

```{r}
facet <- gospels_nrc %>% 
  ggplot(aes(x = sentiment, y = value,
             group = interaction(book, sentiment),
             fill = book, color = book)) +
  geom_polygon(aes(group = word), size = .2, alpha = .5, show.legend = F) +
  scale_x_discrete(limits = order,
                   labels = c("Positive", "Joy", "Anticipation",
                              "Trust", "Surprise", "Negative",
                             "Sadness", "Anger", "Fear", "Disgust")) +
  coord_polar(clip = "off") +
  scale_color_manual(values = c("#eea990", "#854442", "#d73232", "#00b3ff"),
                     labels = c("Matthew", "Mark", "Luke", "John")) + 
  scale_fill_manual(values = c("#eea990", "#854442", "#d73232", "#00b3ff")) +
  labs(caption = "Graphic: Sung Inkyung") +
  ylim(0,40) +
  facet_grid(~ book) +
  theme_minimal() +
  theme(strip.text = element_blank(),
        panel.spacing = unit(2.5, "lines"),
        plot.title = element_blank(),
        plot.caption = element_markdown(size = 13,
                                        family = "Fira Sans Condensed",
                                        hjust = .5,
                                        margin = margin(t = 20)),
        axis.title = element_blank(),
        axis.ticks = element_blank(),
        axis.text.x = element_text(size = 7,
                                   family = "Comfortaa"),
        axis.text.y = element_blank()) 
  
```

```{r}
panel <- (main + facet) + plot_layout(ncol = 1, heights = c(1, 0.3))

ggsave("0315_GospelsSentimentPolygon.png", width = 40, height = 27, units = "cm")
```
