---
title: "WordsFlower3"
author: "Sung Inkyung"
date: '2021 10 6'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(ggforce)
library(tidyverse)
library(patchwork)
library(paletteer)
library(showtext)

font_add_google("Pacifico", "pacifico")
font_add_google("Bebas Neue", "bebas")
showtext_auto()
showtext_opts(dpi = 72)
```


```{r}
word_jul <- c("act", "do", "distinguish", "fashion", "counsel", "place", "brighten", "mourn")

paletteer_d("Redmonder::qMSOGn")
cols_jul <- c("#A9BA9DFF", "#455F51FF", "#549E39FF", "#8AB833FF", "#C0CF3AFF", "#029676FF", "#4AB5C4FF", "#098975FF")

k <- 4
theta <- seq(from = -pi/(2*k), to = 2*pi-pi/(2*k), length.out = k * 50)
x <- cos(k * theta) * cos(theta)
y <- cos(k * theta) * sin(theta)

samuel <- cut(theta, 2*k, labels = word_jul)

df_flower <- tibble(x = x, y = y, samuel = samuel)

plot_legend_labels <- 
  tibble(
    label = word_jul,
    angle_degrees = (90 - 360 * (1:8) / 8),
    angle_radians = angle_degrees * pi / 180,
    angle_text = ifelse(angle_degrees < -90, 
                        angle_degrees + 180, 
                        angle_degrees),
    x = 0.5 * cos(angle_radians),
    y= 0.5 * sin(angle_radians)
  )

fill_jul <- tibble(line = word_jul, 
                   fill = cols_jul)

plot_legend_data <-
  df_flower %>% 
  left_join(fill_jul, by = c("samuel" = "line")) 



plot_jul <- 
  ggplot(plot_legend_data) +
  geom_polygon(aes(x = x, y = y, 
                   fill = fill, 
                   color = fill), 
               size = 1.1) +
  geom_circle(aes(x0 = 0, y0 = 0, r = 0.2), 
              fill = "#672146", 
              color = "#672146", 
              size = 3.5) +
  geom_text(data = plot_legend_labels, 
            aes(x = x, y = y, label = label, 
                angle = angle_text), 
            color = "#ffdab9", 
            size = 35, 
            family = "pacifico") +
  geom_text(aes(x = 0, y = 0, label = "2021\nJuly"), 
            color = "#c6f070",  
            size = 20,
            lineheight = 0.3,
            family = "bebas",
            fontface = "bold") +
  scale_fill_identity() +
  scale_color_identity() +
  coord_equal() +
  theme_void() 
```


```{r}
word_aug <- c("escape", "subdue", "recite", "thin", "smash", "consume", "elapse", "wrong")

paletteer_d("palettesForR::Cool")
cols_aug <- c("#112AC6FF", "#539BE2FF", "#161066FF", "#40234CFF", "#073F93FF", "#2C6CCCFF", "#265121FF", "#04422CFF")

k <- 4
theta <- seq(from = -pi/(2*k), to = 2*pi-pi/(2*k), length.out = k * 50)
x <- cos(k * theta) * cos(theta)
y <- cos(k * theta) * sin(theta)

judges <- cut(theta, 2*k, labels = word_aug)

df_flower <- tibble(x = x, y = y, judges = judges)

plot_legend_labels <- 
  tibble(
    label = word_aug,
    angle_degrees = (90 - 360 * (1:8) / 8),
    angle_radians = angle_degrees * pi / 180,
    angle_text = ifelse(angle_degrees < -90, 
                        angle_degrees+180, 
                        angle_degrees),
    x = 0.5 * cos(angle_radians),
    y= 0.5 * sin(angle_radians)
  )

fill_aug <- tibble(line = word_aug, 
                   fill = cols_aug)

plot_legend_data <-
  df_flower %>% 
  left_join(fill_aug, by = c("judges" = "line")) 



plot_aug <- 
  ggplot(plot_legend_data) +
  geom_polygon(aes(x = x, y = y, 
                   fill = fill, 
                   color = fill), 
               size = 1.1) +
  geom_circle(aes(x0 = 0, y0 = 0, r = 0.2), 
              fill = "#bd007c", 
              color = "#bd007c", 
              size = 3.5) +
  geom_text(data = plot_legend_labels, 
            aes(x = x, y = y, label = label, 
                angle = angle_text), 
            color = "#ffdab9", 
            size = 35, 
            family = "pacifico") +
  geom_text(aes(x = 0, y = 0, label = "2021\nAugust"), 
            color = "#30d5c8",  
            size = 20, 
            lineheight = 0.3,
            family = "bebas",
            fontface = "bold") +
  scale_fill_identity() +
  scale_color_identity() +
  coord_equal() +
  theme_void()
```

```{r}
word_sep <- c("reaffirm", "pronounce", "fast", "rebuild", "display", "nourish", "pierce", "guard")

paletteer_d("colRoz::whitei")
cols_sep <- c("#E5A430FF", "#9C7210FF", "#B77897FF", "#BAB24FFF", "#392821FF", "#9B391BFF", "#457D60FF", "#5A5F9DFF")

k <- 4
theta <- seq(from = -pi/(2*k), to = 2*pi-pi/(2*k), length.out = k * 50)
x <- cos(k * theta) * cos(theta)
y <- cos(k * theta) * sin(theta)

timothy <- cut(theta, 2*k, labels = word_sep)

df_flower <- tibble(x = x, y = y, timothy = timothy)

plot_legend_labels <- 
  tibble(
    label = word_sep,
    angle_degrees = (90 - 360 * (1:8) / 8),
    angle_radians = angle_degrees * pi / 180,
    angle_text = ifelse(angle_degrees < -90, 
                        angle_degrees + 180, 
                        angle_degrees),
    x = 0.5 * cos(angle_radians),
    y= 0.5 * sin(angle_radians)
  )

fill_sep <- tibble(line = word_sep, 
                   fill = cols_sep)

plot_legend_data <-
  df_flower %>% 
  left_join(fill_sep, by = c("timothy" = "line")) 



plot_sep <- 
  ggplot(plot_legend_data) +
  geom_polygon(aes(x = x, y = y, 
                   fill = fill, 
                   color = fill), 
               size = 1.1) +
  geom_circle(aes(x0 = 0, y0 = 0, r = 0.2), 
              fill = "#9a0026", 
              color = "#9a0026", 
              size = 3.5) +
  geom_text(data = plot_legend_labels, 
            aes(x = x, y = y, label = label, 
                angle = angle_text), 
            color = "#ffdab9", 
            size = 35, 
            family = "pacifico") +
  geom_text(aes(x = 0, y = 0, label = "2021\nSeptember"), 
            color = "#00ff85",  
            size = 20, 
            lineheight = 0.3,
            family = "bebas",
            fontface = "bold") +
  scale_fill_identity() +
  scale_color_identity() +
  coord_equal() +
  theme_void() 
```

```{r}
plot <- plot_jul|plot_aug|plot_sep
plot_final <- plot +
  plot_annotation(caption = "Source: Personal Daily Record | Graphic: Sung Inkyung") &
  theme(
    plot.background = element_rect(fill = "black",  
                                   color = NA),
    plot.caption = element_text(size = 50,
                                family = "bebas",
                                color = "gray75",
                                margin = margin(b = 10))
    )

ggsave(here::here("2021", "W1_WordFlower", "2021_WordFlower3.png"), dpi = 300, width = 45, height = 15, units = "cm")
```

