---
title: "Words Flower4"
author: "Sung Inkyung"
date: '2021 12 30'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggforce)
library(tidyverse)
library(patchwork)
library(paletteer)
library(showtext)

font_add_google("Pacifico", "pacifico")
font_add_google("Bebas Neue", "bebas")
showtext_auto()
showtext_opts(dpi = 72)
```


```{r}
word_oct <- c("gather", "venture", "entwine", "vindicate", "shape", "pray", "silence", "prompt")

paletteer_d("Redmonder::qMSOYlOr")
cols_oct <- c("#ACCBF9FF", "#242852FF", "#4A66ACFF", "#629DD1FF", "#297FD5FF", "#7F8FA9FF", "#5AA2AEFF", "#9D90A0FF")

k <- 4
theta <- seq(from = -pi/(2*k), to = 2*pi-pi/(2*k), length.out = k * 50)
x <- cos(k * theta) * cos(theta)
y <- cos(k * theta) * sin(theta)

samuel <- cut(theta, 2*k, labels = word_oct)

df_flower <- tibble(x = x, y = y, samuel = samuel)

plot_legend_labels <- 
  tibble(
    label = word_oct,
    angle_degrees = (90 - 360 * (1:8) / 8),
    angle_radians = angle_degrees * pi / 180,
    angle_text = ifelse(angle_degrees < -90, 
                        angle_degrees + 180, 
                        angle_degrees),
    x = 0.5 * cos(angle_radians),
    y= 0.5 * sin(angle_radians)
  )

fill_oct <- tibble(line = word_oct, 
                             fill = cols_oct)

plot_legend_data <-
  df_flower %>% 
  left_join(fill_oct, by = c("samuel" = "line")) 



plot_oct <- 
  ggplot(plot_legend_data) +
  geom_polygon(aes(x = x, y = y, 
                   fill = fill, 
                   color = fill), 
               size = 1.1) +
  geom_circle(aes(x0 = 0, y0 = 0, r = 0.2), 
              fill = "#672146", 
              color = "#672146", 
              size = 3.5) +
  geom_text(data = plot_legend_labels, 
            aes(x = x, y = y, label = label, 
                angle = angle_text), 
            color = "#ffdab9", 
            size = 35, 
            family = "pacifico") +
  geom_text(aes(x = 0, y = 0, label = "2021\nOctober"), 
            color = "#c6f070",  
            size = 18,
            lineheight = .3,
            family = "bebas",
            fontface = "bold") +
  scale_fill_identity() +
  scale_color_identity() +
  coord_equal() +
  theme_void() 

```


```{r}
word_nov <- c("surround", "engrave", "value", "treasure", "view", "warm", "read", "tread")

paletteer_d("tvthemes::FireNation")
cols_nov <- c("#ECB100FF", "#A10000FF", "#7E605EFF", "#FF4500FF", "#994823FF", "#4B4C4EFF", "#572530FF", "#D1475CFF")

k <- 4
theta <- seq(from = -pi/(2*k), to = 2*pi-pi/(2*k), length.out = k * 50)
x <- cos(k * theta) * cos(theta)
y <- cos(k * theta) * sin(theta)

job <- cut(theta, 2*k, labels = word_nov)

df_flower <- tibble(x = x, y = y, job = job)

plot_legend_labels <- 
  tibble(
    label = word_nov,
    angle_degrees = (90 - 360 * (1:8) / 8),
    angle_radians = angle_degrees * pi / 180,
    angle_text = ifelse(angle_degrees < -90, 
                        angle_degrees+180, 
                        angle_degrees),
    x = 0.5 * cos(angle_radians),
    y= 0.5 * sin(angle_radians)
  )

fill_nov <- tibble(line = word_nov, 
                   fill = cols_nov)

plot_legend_data <-
  df_flower %>% 
  left_join(fill_nov, by = c("job" = "line")) 



plot_nov <- 
  ggplot(plot_legend_data) +
  geom_polygon(aes(x = x, y = y, 
                   fill = fill, 
                   color = fill), 
               size = 1.1) +
  geom_circle(aes(x0 = 0, y0 = 0, r = 0.2), 
              fill = "#bd007c", 
              color = "#bd007c", 
              size = 3.5) +
  geom_text(data = plot_legend_labels, 
            aes(x = x, y = y, label = label, 
                angle = angle_text), 
            size = 35,
            color = "#ffdab9", 
            family = "pacifico") +
  geom_text(aes(x = 0, y = 0, label = "2021\nNovember"), 
            color = "#30d5c8",  
            size = 18,
            lineheight = .3,
            family = "bebas",
            fontface = "bold") +
  scale_fill_identity() +
  scale_color_identity() +
  coord_equal() +
  theme_void() 
```


```{r}
word_dec <- c("thank", "reflect", "equip", "share", "enable", "ascribe", "enter", "reside")

paletteer_d("RSkittleBrewer::smarties")
cols_dec <- c("#FF96C8FF", "#783C8CFF", "#506EBEFF", "#64AA00FF", "#FFFFFF", "#FF6400FF", "#DC0000FF", "#641414FF")

k <- 4
theta <- seq(from = -pi/(2*k), to = 2*pi-pi/(2*k), length.out = k * 50)
x <- cos(k * theta) * cos(theta)
y <- cos(k * theta) * sin(theta)

john <- cut(theta, 2*k, labels = word_dec)

df_flower <- tibble(x = x, y = y, john = john)

plot_legend_labels <- 
  tibble(
    label = word_dec,
    angle_degrees = (90 - 360 * (1:8) / 8),
    angle_radians = angle_degrees * pi / 180,
    angle_text = ifelse(angle_degrees < -90, 
                        angle_degrees+180, 
                        angle_degrees),
    x = 0.5 * cos(angle_radians),
    y= 0.5 * sin(angle_radians)
  )

fill_dec <- tibble(line = word_dec, 
                             fill = cols_dec)

plot_legend_data <-
  df_flower %>% 
  left_join(fill_dec, by = c("john" = "line")) 



plot_dec <- 
  ggplot(plot_legend_data) +
  geom_polygon(aes(x = x, y = y, 
                   fill = fill, 
                   color = fill), 
               size = 1.1) +
  geom_circle(aes(x0 = 0, y0 = 0, r = 0.2), 
              fill = "#9a0026", 
              color = "#9a0026", 
              size = 3.5) +
  geom_text(data = plot_legend_labels, 
            aes(x = x, y = y, label = label, 
                angle = angle_text), 
            color = "#ffdab9", 
            size = 35, 
            family = "pacifico") +
  geom_text(aes(x = 0, y = 0, label = "2021\nDecember"), 
            color = "#00ff85",  
            size = 18,
            lineheight = .3,
            family = "bebas",
            fontface = "bold") +
  scale_fill_identity() +
  scale_color_identity() +
  coord_equal() +
  theme_void() 
```

```{r}
plot <- plot_oct|plot_nov|plot_dec

plot_final <- plot +
  plot_annotation(caption = "Source: Personal Daily Record | Graphic: Sung Inkyung\nCredit: Kaustav Sen") &
  theme(
    plot.background = element_rect(fill = "black",  
                                   color = NA),
    plot.caption = element_text(size = 50,
                                lineheight = 0.3,
                                color = "gray85")
    )

ggsave(here::here("2021", "W1_WordFlower", "2021_WordsFlower4.png"), dpi = 300, width = 45, height = 15, units = "cm")

```

