---
title: "Bible Words Circles"
author: "Sung Inkyung"
date: '2020 11 21'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Source[packcircle package] (https://cran.r-project.org/web/packages/packcircles/packcircles.pdf)
### Source[tidytuesday by Yobanny Samano] (https://github.com/ysamano/TidyTuesday/blob/master/2020/week_16/week_16_hip_hop.R)

```{r}
library(tidyverse)
library(tidytext)
library(ggtext)
library(packcircles)
library(patchwork)
```


```{r}
bible <- readr::read_csv("C:/Users/inkyscope/Documents/projects/data/bible_kjv_new.csv") %>% 
  mutate(Testament = ifelse(book %in% c("Matthew", "Mark", "Luke",
                                        "John", "Acts", "Romans", 
                                        "1 Corinthians", 
                                        "2 Corinthians",  "Galatians",
                                        "Ephesians", "Philippians",
                                        "Colossians", 
                                        "1 Thessalonians",
                                        "2 Thessalonians", 
                                        "1 Timothy", "2 Timothy",
                                        "Titus","Philemon",
                                        "Hebrews", "James", "1 Peter",
                                        "2 Peter", "1 John", "2 John",
                                        "3 John","Jude", "Revelation"), 
                            "New Testament", "Old Testament"))


bible_stop_words <- c(c("art", "thy", "thou", "thine", "thee", "hast", "hath","shalt",
                         "ye", "yea", "saith", "thereof", "wherefore", "lo", "aaron", "aaron's", "aaronites", "abarim"))


bible_words <- bible %>% 
  select(-citation, -verse) %>% 
  unnest_tokens(word, text) %>% 
  anti_join(stop_words) %>% 
  filter(!word %in% bible_stop_words) %>% 
  count(book, word, Testament, sort = T)

total_words <- bible_words %>% 
  group_by(book) %>% 
  summarise(total = sum(n)) %>% 
  arrange(-total)

bible_words <- left_join(bible_words, total_words) %>% 
  mutate(ID = row_number()) %>% 
  filter(n >= 50)

bible_words %>% 
  filter(Testament == "Old Testament") %>% 
  count(word, sort = T) %>% 
  mutate(id = row_number())

```

```{r}
df <- bible_words  %>% 
  mutate(color = case_when(
    Testament == "Old Testament" ~ "#019f66",
    Testament == "New Testament" ~ "#cc31b6",
    TRUE ~ "#ffec1b"
  ))

packing <- bible_words %>% 
  arrange(book) %>% 
  circleProgressiveLayout(sizecol = "n", 
                          sizetype = "area") %>% 
  mutate(radius = radius * .9)

dat.gg <- circleLayoutVertices(packing, npoints = 200)

labels_cir <- df %>% 
  arrange(book) %>% 
  select(ID, n) %>% 
  bind_cols(packing)

words <- df %>% 
  mutate(mark = str_c(ID, ". ", word, " - ", book),
         axis_x = rep(1:7, each = 61, length = n()),
         axis_y = rep(61:1, length = n())) %>% 
  filter(!is.na(mark))

plot_circle <- ggplot() +
  geom_polygon(data = dat.gg,
               aes(x, y, group = id, fill = factor(id)),
               color = NA) +
  geom_text(data = labels_cir,
            aes(x, y, size = n, label = ID),
            color = "#fbe7b6") +
  scale_size_continuous(range = c(1, 3)) +
  scale_fill_manual(values = df$color) +
  coord_equal() +
  theme_void() +
  theme(legend.position = "none")


plot_word <- words %>% 
  ggplot(aes(axis_x, axis_y)) +
  geom_text(aes(label = mark),
            size = 1.4,
            hjust = 0,
            color = "#d3dede") +
  scale_x_continuous(limits = c(.9, 8),
                     expand = c(0.1, 0))+
  scale_y_continuous(limits = c(.5, 61.5),
                     expand = c(0, 0)) +
  theme_void()
  

plot_patches <- plot_circle / plot_word + plot_layout(heights = c(1, .7)) +
  plot_annotation(
    title = "Words of All Books in King James Bible",
    subtitle = "427 words from 39 books by <span style='color:#019f66'>**Old Testament**</span> and<br>27 books by <span style='color:#cc31b6'>**New Testament**</span><br>
    Words appearing <span style='color:#fbe7b6'>**more than 50 times**</span> are selected from each Testament",
    caption = "**Source**: King James Bible | **Graphic**: Sung Inkyung") &
  theme(plot.background = element_rect(fill = "#191c1b",
                                       color = "#191c1b"),
        plot.title = element_text(size = 20, 
                                  face = "bold",
                                  color = "white",
                                  hjust = .5,
                                  margin = margin(t = 20, b = 10)),
        plot.subtitle = element_markdown(size = 14, 
                                        lineheight = .7,
                                        color = "white",
                                         hjust = 0.5,
                                         margin = margin(b = 5)),
        plot.caption = element_markdown(size = 7,
                                        color = "#f5f5f5",
                                        hjust = 1, 
                                        margin = margin(t = 20, b= 5, r = 10)))

ggsave(here::here("2020", "1121_BibleWordsCircles", "1121_BibleWordsCircles.png"), width = 21, height = 24, units = "cm")

```
