---
title: "Seeds of Words"
author: "Sung Inkyung"
date: '2020 12 20'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidytext)
library(ggtext)
library(showtext)

font_add_google("Saira")
font_add_google("Sarabun")
font_add_google("Roboto Condensed")

showtext_opts(dpi = 320)
showtext_auto(enable = TRUE)
```


```{r}
bible_words <- readr::read_csv("C:/Users/inkyscope/Documents/projects/data/bible_kjv_new.csv") %>% 
  select(book, text) %>% 
  unnest_tokens(word, text) %>% 
  anti_join(stop_words) %>% 
  filter(word %in% c("lord", "word", "time", "spirit", "peace", "glory", "dwell")) %>% 
  count(word, book, sort = T, name = "count") 

```


```{r}
bible <- bible_words %>% 
  mutate(word_level = case_when(
    word == "dwell" ~ 7,
    word == "glory" ~ 6,
    word == "peace" ~ 5,
    word == "spirit" ~ 4,
    word == "time" ~ 3,
    word == "word" ~ 2,
    word == "lord" ~ 1
  )) 

words <- c("lord", "word", "time", "spirit", "peace", "glory", "dwell")

round_word <- bible_words %>%  
  filter(word %in% words) %>%
  group_by(word) %>% 
  summarise(total = n()) %>% 
  arrange(-total) 



```

```{r}
rect <- data.frame(
  x1 = c(0.4),
  x2 = c(1.6),
  y1 = c(0, 4.5, 6.5, 8.5), 
  y2 = c(3.5, 5.5, 7.5, 9.5)
  )
  
```


```{r}
legend_order <- c("dwell", "glory", "peace", "spirit", "time", "word", "lord")
colors <- c('#00ff00', '#08b8b8', '#0000ff', 
            '#e591b4', '#e8215a', '#fcdb40', '#6a2225')

plot <- bible %>% 
  ggplot() + 
  geom_rect(data = rect, 
            aes(xmin = x1, xmax = x2,
                ymin = y1, ymax = y2), 
            fill = "#d8b361") +
  geom_jitter(aes(x = 1, y = word_level + 2, 
                 color = word), 
              size = 2.5,
             na.rm = T) +
  annotate(geom="text", x = 1, y = 0, 
           size = 11,
           label="L O R D",
           family = "Sarabun",
           fontface = "bold",
           color= '#6a2225') +
  annotate(geom="text", x = .4, y = 4, 
           size = 7,
           family = "Sarabun",
           label="W O R D",
           fontface = "bold",
           color= '#fcdb40') +
  annotate(geom="text", x = .4, y = 5, 
           size = 7,
           family = "Sarabun",
           label="T I M E",
           fontface = "bold",
           color= '#e8215a') +
  annotate(geom="text", x = .4, y = 6, 
           size = 7,
           family = "Sarabun",
           label="S P I R I T",
           fontface = "bold",
           color= '#e591b4') +
  annotate(geom="text", x = .4, y = 7, 
           size = 7,
           family = "Sarabun",
           family = "Sarabun",
           label="P E A C E",
           fontface = "bold",
           color= '#0000ff') +
  annotate(geom="text", x = .4, y = 8, 
           size = 7,
           family = "Sarabun",
           label="G L O R Y",
           fontface = "bold",
           color= '#08b8b8') +
  annotate(geom="text", x = .4, y = 9, 
           size = 7,
           family = "Sarabun",
           label="D W E L L",
           fontface = "bold",
           color= '#00ff00') +
  scale_color_manual(values = colors,
                     breaks = legend_order)  +
  coord_polar(start = pi) +
  labs(title = "S e e d s o f W o r d s",
       caption = "**Graphic**: Sung Inkyung") + 
  theme_void() + 
  theme(legend.position = "none",
        plot.background = element_rect(fill = '#081a3d', 
                                       color = "#081a3d"),
        panel.background = element_blank(),
        plot.title = element_text(size = 48,
                                  family = "Saira",
                                  color = "#e4eaed",
                                  hjust = .5,
                                  margin = margin(t = 30, b= 10)),
        plot.caption = element_markdown(size = 13,
                                        family = "Roboto Condensed",
                                        color = "#e4eaed",
                                        hjust = .5,
                                        margin = margin(t = 20, b = 10)),
       plot.margin = margin(10, 10, 10, 10))

ggsave("1220_SeedsofWords.png", width = 30, height = 30, units = "cm")
```

```{r}
plot <- bible %>% 
  ggplot() + 
  geom_rect(data = rect, 
            aes(xmin = x1, xmax = x2,
                ymin = y1, ymax = y2), 
            fill = "#e8c14d") +
  coord_polar(start = pi) 
```

