---
title: "Psalms Circles"
author: "Sung Inkyung"
date: '2020 7 5 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Source[tidytuesday by ysamano] (https://github.com/ysamano/TidyTuesday/blob/master/2020/week_27/week_27_x-men.R)
```{r}
library(tidyverse)
library(tidytext)
library(ggtext)
library(ggforce)
library(here)

```


```{r}
psalms <- readr::read_csv("C:/Users/inkyscope/Documents/projects/data/bible_kjv_new.csv") %>% 
  filter(book == "Psalms") %>% 
  select(-c(citation, verse))
     

psalms_words <- psalms %>%
  unnest_tokens(word, text) %>%
  anti_join(stop_words) %>%
  filter(!word %in% c("thou", "thy", "thine", "hast", "art",
                      "shalt", "thee", "hath", "ye", "lord", "god")) %>% 
  group_by(chapter, word) %>% 
  summarise(total = n()) %>% 
  filter(total >= 3)

psalms_words %>% 
  group_by(chapter) %>% 
  summarize(n = sum(total)) %>% 
  arrange(desc(n))


psalms_words %>% 
  filter(total > 20)

```


```{r}
psalms_radius <- function(total_var, radio) {
  
  tibble(variable = 1:total_var,
         radio = seq(radio, radio*total_var, length.out = total_var))
}

df_psalms <- psalms_words %>% 
  group_by(chapter) %>% 
  summarise(total = n()) %>% 
  mutate(axis_x = rep(seq(2, 20, by = 2), length = n()),
         axis_y = rep(seq(36, 2, by = -2), each = 10, length = n()),
         chapter = if_else(chapter == 1, "Chapter 1", as.character(chapter)))


data_graph <- df_psalms %>% 
  group_by(chapter) %>% 
  mutate(list(psalms_radius(total, 0.1))) %>% 
  unnest()
```


```{r}
psalms_plot <- ggplot(data_graph) +
  geom_circle(aes(x0 = axis_x,
                  y0 = axis_y,
                  r = radio),
              color = "#00afc4",
              n = 700,
              size = 0.3) +
  geom_text(data = df_psalms,
            aes(axis_x, axis_y - 0.8, label = chapter),
            size = 2.5, 
            colour = "#eee9e9") +
  labs(title = "The Book of Psalms by Word Frequency",
       subtitle = "Illustrated below is showing chapter based on words frequency appeared more than 3 times.<br> Unsurprisingly chapter 119 has the highest number of words, followed by 78, 89, 18, 37, 68,<br>107, 136, 105, 106. As well, chapter 119 includes the most repeated words, followed by<br>chapter 136 including **endureth** and **mercy**. In the chapter 119, **commandments**,<br>**law**, **precepts**, **statutes**, **testimonies** appear more then 20 times and<br>**word** repeats 38 times.",
       caption = "Graphic: Sung Inkyung") +
  coord_fixed() +
  theme_minimal() +
  theme(plot.background = element_rect(fill = "#001113"),
        plot.title = element_text(color = "#eee9e9",
                                  size = 24,
                                  hjust = .5,
                                  margin = margin(t = 10, b = 10)),
        plot.subtitle = element_markdown(color = "#eee9e9",
                                         size = 16,
                                         lineheight = 1.1,
                                         hjust = .5,
                                         margin = margin(b = 15)),
        plot.caption = element_text(hjust = .5,
                                    size = 9,
                                    color = "#cdc9c9",
                                    margin = margin(t = 20, b = 10)),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text = element_blank(),
        axis.title = element_blank())

ggsave(here("figures", "PsalmsCircles.png"), width = 28, height= 36, units = "cm")

```

