---
title: "Prepositions Pairs"
author: "Sung Inkyung"
date: '2020 12 05'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidytext)
library(ggtext)
library(igraph)
library(ggraph)
library(showtext)

font_add_google("Oswald")
font_add_google("Source Sans Pro")
font_add_google("Lato")

showtext_opts(dpi = 320)
showtext_auto(enable = TRUE)
```


```{r}
bible <- readr::read_csv("C:/Users/inkyscope/Documents/projects/data/bible_kjv_new.csv") 

```


```{r}
bible_stop_word <- c("his", "him", "a", "their", "all", "my", "me", "them", "that", "all", "her", "your", "her",  "this", "and", "it", "us", "it", "mine", "those", "my", "an", "any", "our", "to", "whom", "and", "of", "these", "what", "which", "whose", "one", "himself", "themselves", "at", "you", "unto", "no", "by", "you", "for", "among", "thence", "before", "off", "i", "he", "ever", "we", "there", "if", "in", "thus", "us",
                     "thee", "thou", "thine", "thy", "ye", "lo", "whosoever", "therewith",
                     "jerusalem", "egypt", "israel", "jordan", "beelzebub", "macedonia", "moses", "henceforth")

bible_bigrams <- bible %>% 
  select(-citation, -chapter, -verse) %>% 
  unnest_tokens(bigram, text, toke = "ngrams", n = 2) 

bigrams_separate <- bible_bigrams %>% 
  separate(bigram, c("word1", "word2"), sep = " ") %>% 
  filter(!word2 %in% stop_words$word)


df_preposition <- bigrams_separate  %>% 
  rename(preposition = word1,
         word = word2) %>% 
  filter(preposition %in% c("in",  "through", "with",  "by", "for", "from")) %>% 
  filter(!word %in% bible_stop_word) %>% 
  count(preposition, word, sort = T) %>% 
  filter(n >= 8) %>% 
  graph_from_data_frame()



communities <- walktrap.community(df_preposition)

V(df_preposition)$color <- as.character(membership(communities))

V(df_preposition)$dgr <- degree(df_preposition, mode = "all")
```

```{r}
## plot
set.seed(2020)

net_plot <- df_preposition %>% 
  ggraph(layout = layout_nicely(df_preposition)) +
  geom_node_point(
    aes(color = color,
        size = dgr)) +
  geom_edge_fan(
    aes(alpha = n),
    color = "white",
    arrow = grid::arrow(length = unit(.15, "cm"))) +
  geom_node_text(
    aes(label = name,
        size = 9),
    family = "Source Sans Pro",
    color = "white",
    repel = T) +
  scale_color_manual(values = c("#ffce07", "#0cbb06", "#9e1252", "#c685d6", 
                                "#59a19f",  "#8b645f")) +
  labs(title = "Preposition Pairs Network",
       subtitle = "**god**, **faith**, **righteousness** are core words<br>most repeatedly connected with the chosen prepositions",
       caption = "**Graphic**: Sung Inkyung") +
  theme(panel.background = element_rect(fill = "#3a425d"),
        plot.background = element_rect(fill = "#3a425d",
                                       color = "#3a425d"),
        legend.position = "none",
        plot.title = element_text(size = 24,
                                  family = "Oswald",
                                  hjust = .5,
                                  color = "gray75",
                                  face = "bold",
                                  margin = margin(t = 10, b = 7)),
        plot.subtitle = element_markdown(size = 16,
                                         family = "Lato", 
                                         hjust = .5,
                                         color = "gray75",
                                         margin = margin(b = 15)),
        plot.caption = element_markdown(size = 9,
                                        family = "Lato",
                                        color = "gray75",
                                        hjust = 1,
                                    margin = margin(t = 30, b = 20)),
        plot.margin = margin(20, 60, 10, 20))

ggsave("1205_PrepositionsPairsNetwork.png", width = 28, height = 18, units = "cm")
```

