---
title: "Share2"
author: "Sung Inkyung"
date: '2021 12 15'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(geomtextpath)
library(ggplot2)
library(patchwork)
library(showtext)

font_add_google("Julius Sans One")
font_add_google("Caveat Brush")
font_add_google("Rajdhani")
font_add_google("Finger Paint")
showtext_opts(dpi = 320)
showtext_auto(enable = TRUE)
```


```{r}
df <- data.frame(x = c(1, 1000),
                 y = 1,
                 text = "All will share alike")

p1 <- ggplot(df, aes(x, y, label = text)) +
  geom_textpath(size = 11, 
                family = "JUlius Sans One",
                color = "#30315a",
                include_line = F) +
  ylim(c(0.9, 1.06)) +
  coord_polar() +
  theme_void()

p2 <- ggplot(df, aes(x, y, label = text)) +
  geom_textpath(size = 11, 
                family = "Finger Paint",
                color = "#912b52",
                include_line = F) +
  ylim(c(0.9, 1.06)) +
  coord_polar() +
  theme_void()

p3 <- ggplot(df, aes(x, y, label = text)) +
  geom_textpath(size = 11, 
                family = "Caveat Brush",
                color = "#fb9800",
                include_line = F) +
  ylim(c(0.9, 1.06)) +
  coord_polar() +
  theme_void()

p4 <- ggplot(df, aes(x, y, label = text)) +
  geom_textpath(size = 11, 
                family = "Rajdhani",
                color = "#590456",
                include_line = F) +
  ylim(c(0.9, 1.06)) +
  coord_polar() +
  theme_void()

```


```{r}
patchwork <- (p1 | p2)/(p3 | p4) 

p <- patchwork + plot_annotation(
  caption = "Graphic: Sung Inkyung"
) &
  theme(plot.caption = element_text(size = 9,
                                    family =  "Figer Paint"))

ggsave("Share2.png")

```
