---
title: "Job vs His Friends"
author: "Sung Inkyung"
date: '2021 10 28'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Source [tidytuesday by @gkaramanis] (https://github.com/gkaramanis/tidytuesday/blob/master/2021/2021-week8/employed.R)
### Source 
```{r}
library(tidyverse)
library(tidytext)
library(ggfx)
```


```{r}
job <- readr::read_csv("C:/Users/inkyscope/Documents/projects/data/bible_kjv_new.csv") %>% 
    filter(book == "Job") %>% 
    select(-c(book, citation, verse))
```


```{r}
job_words <- job %>% 
   filter(chapter %in% 4:37) %>% 
   mutate(
    character = case_when(
      chapter %in% c("6", "7", "9", "10", "12", "13", "14", "16", "17", "19", "21", "23", "24", "26", "27", "28", "29", "30", "31") ~ "Job",
      chapter %in% c("4", "5", "15", "22") ~ "Eliphaz",
      chapter %in% c("8", "18", "25") ~"Bildad",
      chapter %in% c("11", "20") ~ "Zophar",
      chapter %in% c("32", "33", "34", "35", "36", "37") ~"Elihu",
      TRUE ~ as.character(chapter)
      )) %>% 
  unnest_tokens(word, text) %>%
  anti_join(stop_words) %>%
  filter(!word %in% c("thou", "thy", "thine", "hast", "art", "mine",
                      "shalt", "thee", "hath", "ye", "yea", "thereof", "job", "god", "day", "doth", "canst", "cometh", "wilt", "dost", "wherefore", "shouldes", "lo")) %>% 
  count(character, word, sort = T) %>% 
  slice(1:40)
```


```{r}
df <- job_words %>% 
  filter(character != "Elihu") %>% 
  mutate(character = case_when(character %in% c("Eliphaz", "Bildad", "Zophar") ~ "Friends",
                               TRUE ~ "Job")) %>% 
  mutate(prc = round(n / n(), 2)) %>% 
  mutate(
    word = fct_reorder(toupper(word), prc),
    str_width = strwidth(word, units = "inches") * 25.4,
    str_ratio = max(str_width)/str_width,
    text_size = 5.5 * str_ratio,
    tile_height = text_size/10
  ) %>% 
  arrange(prc) %>% 
  mutate(y = cumsum(lag(tile_height/2, default = 0) + tile_height/2))
  
  
```



```{r}
pal <- c("#1b5e65", "#b35253") # job, friends

plot <- df %>% 
  ggplot() +
  as_reference(
    geom_rect(aes(xmin = -0.5,
                  xmax = -0.5 + (prc),
                  ymin = y - (tile_height * 0.5),
                  ymax = y + (tile_height * 0.5))),
               id = "Job") +
   with_blend(
    geom_text(aes(
      x = 0,
      y = y,
      label = word,
      size = text_size
    ),
    color = pal[1]),
    bg_layer = "Job",
    blend_type = "in"
  ) +
  as_reference(
    geom_rect(aes(xmin = 0.5 -(1 - prc),
                  xmax = 0.5,
                  ymin = y - (tile_height * 0.5),
                  ymax = y + (tile_height * 0.5))),
               id = "Friends") +
  with_blend(
    geom_text(aes(
      x = 0,
      y = y,
      label = word,
      size = text_size
    ),
    color = pal[2]),
    bg_layer = "Friends",
    blend_type = "in"
  ) +
  annotate("text", x = -0.12, y = 42.2, 
           label = "More from Job", angle = 90, 
           color = pal[1],  fontface = "bold", size = 30) +
  annotate("text", x = 0.12, y = 6.5, 
           label = "More form his friends", angle = 270, 
           color = pal[2],  fontface = "bold", size = 30) +
  #caption
  annotate("text", x = -0.48, y = 17.5, 
           label = "Source: KJV | Graphic: Sung Inkyung", 
           angle = 90,
           hjust = 0, 
           color = "grey30", 
           size = 18) +
  scale_size_identity() +
  coord_cartesian(expand = FALSE, 
                  clip = "off") +
  labs(title = "Job vs HIS FRIENDS:ELIPHAZ, BILDAD, ZOPHAR") +
  theme_void() +
  theme(
    legend.position = "none",
    plot.background = element_rect(fill = "gray90", 
                                   color = NA),
    plot.title = element_text(face = "bold", 
                              hjust = 0.5, 
                              size = 80, 
                              margin = margin(5, 0, 20, 0)),
    plot.margin = margin(20, 0, 20, 0)
  )

ggsave( "Job_Friends.png", width = 32, height = 40, units = "cm")
```