---
title: "EphesiansCross"
author: "Sung Inkyung"
date: '2021 5 1'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(visNetwork)
library(here)
```


```{r}
cross_refs <- read.csv("C:/Users/inkyscope/Documents/projectR/inkyscroll/data/Ephesians.csv")

#View(cross_refs)

df_eph <- cross_refs %>% 
  filter(grepl("Eph\\.1\\.|Eph\\.2\\.|Eph\\.3\\.|Eph\\.4\\.|Eph\\.5\\.|Eph\\.6\\.", From.Verse, fixed = F)) %>% 
  rename(to = To.Verse,
         from = From.Verse) %>% 
  select(from, to) %>% 
  mutate(weight = 5,
         level = 3) %>% 
  filter(to != "na")

hierarchy <- tibble(to = c(unique(df_eph$from))) %>% 
  mutate(from = gsub("(^.*\\..*)(\\...*)", "\\1", to),
         level = 2, 
         weight = 10)

top <- tibble(to = unique(grep("Eph", hierarchy$from, value = T))) %>%
  mutate(from = "Ephesians",
         level = 1, 
         weight = 20)

links <- df_eph %>% 
  rbind(hierarchy) %>% 
  rbind(top)


nodes <- tibble(id = unique(c(links$from, links$to))) %>%
  mutate(chapter = case_when(grepl("Eph.", id) ~ gsub("(^.*\\..*)(\\...*)", "\\1", id),
                             TRUE ~ gsub("([Aa-z])(\\..*)", "\\1", id)),
         overarching = factor(case_when(grepl("Eph.", id) ~ "Ephesians",
                                        TRUE ~ "Bible")),
         shape = "dot",
         shadow = T,
         label = id,
         size = 30,
         borderwidth = 2, 
         font.size = 50,
         font.color = "#8d96a5",
         color.background = case_when(overarching == "Ephesians" ~ "#32a852",
                                      overarching == "Bible" ~ "#696969"),
         color.border = "#656f80",
         color.highlight = case_when(overarching == "Ephesians" ~ "#32a852",
                                     overarching == "Bible" ~ "#696969"),
         color.highlight.border = "#656f80")

plot_eph <- visNetwork(nodes, links, width = "100%", height = "900px",
                      main = list(text = "<b>A B I D E&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;MAY 2021<b>",
                                  style = "color:#314757;font-size:30px;font-face:bold; text-align:center;"),
                      submain = list(text = "Illustrated below that it links each verse of Ephesians with other biblical books.<br>It is reflected series of sermons delivered by Pastor Cho Jung Min<br>between 2020.11.22 and 2021.3.7 for 16weeks at Basic Church in Seoul Korea.",
                                     style = "color:#314757;font-size:24px;text-align:center;"),
                      footer = list(text = "Source: www.openbible.info | Graphic: Sung Inkyung | Credit: @carathompson",
                                    style = "color:#314757;font-size:12px;text-align:center;")) %>% 
  visOptions(highlightNearest = list(enabled = T, 
                                     degree = 1, 
                                     hover = F),
             autoResize = T) %>% 
  visInteraction(hover = T, 
                 selectConnectedEdges = T, 
                 dragNodes = T, 
                 dragView = T,
                 zoomView = F) %>% 
  visIgraphLayout(physics = T, 
                  randomSeed = 123) %>% 
  visPhysics(solver = "forceAtlas2Based",
             forceAtlas2Based = list(gravitationalConstant = -300),
             stabilization = F) %>% 
  visEvents(type = "once",
            beforeDrawing = "function() {
            this.moveTo({scale:0.2})}") %>% 
  visEvents(type = "on",
            selectNode = "function() {
            this.moveTo({scale:0.35})}") %>% 
  visEvents(type = "on",
            deselectNode = "function() {
            this.moveTo({scale:0.2})}")
                                      
##Export plot....
visSave(graph = plot_eph, file = "C:/Users/inkyscope/Documents/projectR/inkyscroll/2021/W17_WordCross/EphesiansCross.html",
        selfcontained = T)
```

