---
title: "Word Cross"
author: "Sung Inkyung"
date: '2021 4 25 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Source[30DayChallenge](https://github.com/cararthompson/30DayChartChallenge/blob/main/scripts/3.1_correlation.R)
### Source[Silent Lines by Cara Thompsom] (https://silentlines.co.uk/portfolio-items/abide-psalms.html)
```{r}
library(tidyverse)
library(visNetwork)
```


```{r}

cross_refs <- read.delim("C:/Users/inkyscope/Documents/projectR/inkyscroll/data/cross_references.txt")

View(cross_refs)

df_cr <- cross_refs %>% 
  filter(grepl("Ps\\.1\\.|Ps\\.16\\.|Ps\\.31\\.|Ps\\.103\\.|Ps\\.143\\.", From.Verse, fixed = F) &
           grepl("Matt.|Mark.|Luke.|^John.", To.Verse)) %>% 
  rename(to = To.Verse,
         from = From.Verse) %>% 
  select(from, to) %>% 
  mutate(weight = 5,
         level = 3)

hierarchy <- tibble(to = c(unique(df_cr$from))) %>% 
  mutate(from = gsub("(^.*\\..*)(\\...*)", "\\1", to),
         level = 2, 
         weight = 10)

top <- tibble(to = unique(grep("Ps", hierarchy$from, value = T))) %>%
  mutate(from = "Psalms",
         level = 1, 
         weight = 20)

links <- df_cr %>% 
  rbind(hierarchy) %>% 
  rbind(top)


nodes <- tibble(id = unique(c(links$from, links$to))) %>%
  mutate(chapter = case_when(grepl("Ps.", id) ~ gsub("(^.*\\..*)(\\...*)", "\\1", id),
                             TRUE ~ gsub("([Aa-z])(\\..*)", "\\1", id)),
         overarching = factor(case_when(grepl("Ps.", id) ~ "Psalms",
                                        TRUE ~ "Gospels")),
         shape = "dot",
         shadow = T,
         label = id,
         size = 20,
         borderwidth = 2, 
         font.size = 30,
         font.color = "#8d96a5",
         color.background = case_when(overarching == "Psalms" ~ "#6857ab",
                                      overarching == "Gospels" ~ "#fcba03"),
         color.border = "#656f80",
         color.highlight = case_when(overarching == "Psalms" ~ "#6857ab",
                                     overarching == "Gospels" ~ "#fcba03"),
         color.highlight.border = "#656f80")

plot_cr <- visNetwork(nodes, links, width = "100%", height = "900px",
                      main = list(text = "<b>A B I D E&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;April 2021<b>",
                                  style = "color:#314757;font-size:30px;font-face:bold; text-align:center;"),
                      submain = list(text = "How Psalms Chapter 1, 16, 31, 103, 143 and Gospels Network with Each Other",
                                     style = "color:#314757;font-size:24px;text-align:center;"),
                      footer = list(text = "Source: www.openbible.info | Graphic: Sung Inkyung | Credit: @carathompson",
                                    style = "color:#314757;font-size:12px;text-align:center;")) %>% 
  visOptions(highlightNearest = list(enabled = T, 
                                     degree = 1, 
                                     hover = F),
             autoResize = T) %>% 
  visInteraction(hover = T, 
                 selectConnectedEdges = T, 
                 dragNodes = T, 
                 dragView = T,
                 zoomView = F) %>% 
  visIgraphLayout(physics = T, 
                  randomSeed = 123) %>% 
  visPhysics(solver = "forceAtlas2Based",
             forceAtlas2Based = list(gravitationalConstant = -300),
             stabilization = F) %>% 
  visEvents(type = "once",
            beforeDrawing = "function() {
            this.moveTo({scale:0.2})}") %>% 
  visEvents(type = "on",
            selectNode = "function() {
            this.moveTo({scale:0.35})}") %>% 
  visEvents(type = "on",
            deselectNode = "function() {
            this.moveTo({scale:0.2})}")
                                      
##Export plot....
visSave(graph = plot_cr, file = "C:/Users/inkyscope/Documents/projectR/inkyscroll/2021/W17_WordCross/WordCross.html",
        selfcontained = T)

```