---
title: "Sentiment Calendar 2021"
author: "Sung Inkyung"
date: '2021 11 10'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Source[tidytuesday by Ijeamak Aanyene] (https://github.com/Ijeamakaanyene/tidytuesday/blob/master/scripts/2020_09_animal_crossing.Rmd)
```{r}
library(tidyverse)
library(tidytext)
library(ggtext)
library(lubridate)
library(showtext)

font_add_google("Roboto Condensed", "roboto")
font_add_google("Comfortaa", "comfortaa")
showtext_auto()

theme_set(theme_minimal())
```


```{r}
word_calendar <- read.csv("C:/Users/inkyscope/Documents/projectR/inkyscroll/data/wordcalendar_2021.csv") %>% 
  select(month, day, word) %>% 
  mutate(month = month.name[month])
```


```{r}
# Calendar
cal <- tibble(
  date = seq(ymd(20210101), ymd(20211231), by = 1)
) %>% 
  mutate(week = as.numeric(format(date, "%U"))) 
  
sentiment_calendar <- cbind(cal, word_calendar) %>% 
  left_join(get_sentiments("nrc")) %>%
  mutate_if(is.character, ~replace(., is.na(.), "neutral")) %>% 
  group_by(date, sentiment, word) %>% 
  mutate(counts = n()) %>% 
  mutate(weekday = weekdays(date),
         weekday = case_when(weekday == "일요일" ~ "Sun",
                             weekday == "월요일" ~ "Mon",
                             weekday == "화요일" ~ "Tue",
                             weekday == "수요일" ~ "Wed",
                             weekday == "목요일" ~ "Thur",
                             weekday == "금요일" ~ "Fri",
                             weekday == "토요일" ~ "Sat"),
         weekday = factor(weekday, c("Sun", "Mon", "Tue", "Wed", "Thur", "Fri", "Sat")),
         month = factor(month, c("January", "February", "March", "April",
                                 "May", "June", "July", "August",
                                 "September", "October", "November", "December")),
         week = week(date),
         label = paste0(weekday, "<br>", day))


duplicates <- sentiment_calendar %>% 
  group_by(date) %>% 
  summarise(counts = n())

```

```{r}
library(paletteer)
paletteer_d("basetheme::royal")
```

```{r}
pals <- c(positive = "#1175BBFF",
          negative = "#B33941FF",
          trust = "#2E8B57FF", 
          anticipation = "#4AC6AEFF",
          fear = "#997950FF",
          joy = "#E93FBCFF",
          anger = "#EF7215FF",
          sadness = "#7852A9FF",
          surprise = "#E27069FF",
          disgust = "#DBA520FF",
          neutral = "#CBC4BC")

plot <- sentiment_calendar %>% 
  ggplot(aes(x = day, y = fct_rev(month),
             fill = sentiment, label = label, lineheight = 0.7)) +
  geom_tile(color = "white", 
            width = 1, height = 0.75) +
  geom_richtext(fill = NA,
                label.color = NA,
                color = "white",
                size = 6) +
  scale_fill_manual(values = pals) +
  scale_x_continuous(expand = c(0.01, 0)) +
  labs(x = "",
       y = "",
       fill = "",
       title = "Daily Sentiment 2021",
       subtitle = "<span style = 'color:#1175BBFF'>**positive**</span>,
       <span style = 'color:#B33941FF'>**negative**</span>,
       <span style = 'color:#2E8B57FF'>**trust**</span>,
       <span style = 'color:#4AC6AEFF'>**anticipation**</span>,
       <span style = 'color:#997950FF'>**fear**</span>,
       <span style = 'color:#E93FBCFF'>**joy**</span>,
       <span style = 'color:#EF7215FF'>**anger**</span>,
       <span style = 'color:#7852A9FF'>**sadness**</span>,
       <span style = 'color:#E27069FF'>**surprise**</span>,
       <span style = 'color:#DBA520FF'>**disgust**</span>,
       <span style = 'color:#CBC4BC'>**neutral**</span>",
       caption = "Source: Personal Daily Word Table | Graphic: Sung Inkyung"
       ) +
  theme(legend.position = "none",
        plot.background = element_blank(),
        panel.background = element_blank(),
        plot.title = element_text(size = 50, 
                                  hjust = 0.5,
                                  family = "roboto",
                                  face = "bold",
                                  margin = margin(t = 10, b = 5)),
        plot.subtitle = element_markdown(size = 40,
                                         hjust = 0.5,
                                         lineheight = 0.4,
                                         family = "roboto",
                                         margin = margin(b = 15)),
        plot.caption = element_text(size = 24,
                                    hjust = 0.5,
                                    family = "roboto",
                                    margin = margin(t = 20)),
        panel.grid = element_blank(),
        axis.title = element_blank(),
        axis.text.y = element_text(size = 32, 
                                   family = "comfortaa",
                                   face = "bold"),
        axis.text.x = element_blank(),
        axis.ticks = element_blank(),
        plot.margin = margin(10, 10, 10, 10))

ggsave("Sentiment_Calendar.png", width = 20, height = 18, units = "cm")

```

