---
title: "Random Words"
author: "Sung Inkyung"
date: '2021 1 30'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Source [tidytuesday by Yabonny Samano] (https://github.com/ysamano/TidyTuesday/blob/master/2021/week_03/TT_2021_03.R)
```{r}
library(tidyverse)
library(tidytext)
library(ggtext)
library(ggfittext)
library(treemap)
library(scales)
library(glue)
```


```{r}
bible <- readr::read_csv("C:/Users/inkyscope/Documents/projects/data/bible_kjv_new.csv") %>% 
  mutate(testament = ifelse(book %in% c("Matthew", "Mark", "Luke",
                                        "John", "Acts", "Romans", 
                                        "1 Corinthians", 
                                        "2 Corinthians",  "Galatians",
                                        "Ephesians", "Philippians",
                                        "Colossians", 
                                        "1 Thessalonians",
                                        "2 Thessalonians", 
                                        "1 Timothy", "2 Timothy",
                                        "Titus","Philemon",
                                        "Hebrews", "James", "1 Peter",
                                        "2 Peter", "1 John", "2 John",
                                        "3 John","Jude", "Revelation"), "New Testament", "Old Testament"))
```


```{r}
bible_stop_words <- c(c("art", "thy", "thou", "thine", "thee", "hast", "hath","shalt",
                         "ye", "yea", "saith", "thereof", "wherefore", "lo", "aaron", "aaron's", "aaronites", "abarim")) 

df <- bible %>% 
  select(book, testament, text) %>% 
  unnest_tokens(word, text) %>% 
  filter(!word %in% bible_stop_words) %>% 
  anti_join(stop_words, by = "word") %>% 
  group_by(word, testament) %>% 
  summarise(total = n()) %>% 
  ungroup() %>% 
  slice_sample(n = 500, order_by = total) %>% 
  mutate(id_tree = row_number())


data_tree <- treemap(df,
                     index = c("word"),
                     vSize = "total",
                     type = "categorical",
                     vColor = "testament",
                     algorithm = "pivotSize",
                     sortID = "id_tree",
                     mirror.y = TRUE,
                     mirror.x = TRUE,
                     border.lwds = .7,
                     aspRatio = 5/3)

data_ggplot <- data_tree[["tm"]] %>% 
  as_tibble() %>% 
  arrange(desc(vSize)) %>% 
  mutate(rank = row_number(),
         xmax = x0 + w,
         ymax = y0 + h,
         label_word = str_glue("{word}\n({comma(vSize, accuracy = 1)})"))

plate_tree <- tibble(label = c("**Illustrated above**",
                                "Each rectangle represents a word",
                                "The size corresponds to the number of words",
                                "The color indicates Testament of Bible,
                                <span style = 'color:#534723'>**Old Testament**</span> and <span style = 'color:#856670'>**New Testament**</span>"),
                      x = c(.5, .5, .5, .5),
                      y = c(-0.07, -0.1, -0.13, -0.16))

p1 <- ggplot(data_ggplot) +
  geom_rect(aes(xmin = x0,
                ymin = y0,
                xmax = xmax,
                ymax= ymax,
                fill = vColor),
            size = 0.3,
            colour = "#432417",
            alpha = 0.9) +
  geom_fit_text(data = data_ggplot %>% filter(rank <= 200),
                aes(xmin = x0, 
                    xmax = xmax, 
                    ymin = y0,
                    ymax = ymax,
                    label = label_word),
                colour = "#bfbeb2",
                min.size = 4,
                reflow = TRUE) +
  geom_richtext(data = plate_tree,
                aes(x, y, label = label), 
                size = 3.5,
                color = "#bfbeb2",
                fill = NA,
                label.color = NA,
                hjust = 0.5) +
  labs(title = "Random Samples of Words",
       caption = "Source: King James Bible | Graphic: Sung Inkyung") +
  scale_fill_manual(values = c("#856670", "#534723")) +
  theme_void() +
  theme(text = element_text(colour ="#bfbeb2"),
        legend.position = "none",
        plot.background = element_rect(fill = "#432417",
                                       colour = "#432417"),
        plot.title = element_text(size = 25,
                                  hjust = 0.5),
        plot.caption = element_text(size = 9,
                                    hjust = 0.5),
        plot.margin = margin(30, 10, 20, 10))

ggsave(here::here("2021", "W6_WordTree", "W6_RandomWordsTree.png"), width = 35.5, height = 20.5, units = "cm")
```
