---
title: "Untitled"
author: "Sung Inkyung"
date: '2020 12 13 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidytext)
library(scales)
library(SnowballC)
```


```{r}
bible <- readr::read_csv("C:/Users/inkyscope/Documents/projects/data/bible_kjv_new.csv") %>% 
  mutate(testament = ifelse(book %in% c("Matthew", "Mark", "Luke",
                                        "John", "Acts", "Romans", 
                                        "1 Corinthians", 
                                        "2 Corinthians",  "Galatians",
                                        "Ephesians", "Philippians",
                                        "Colossians", 
                                        "1 Thessalonians",
                                        "2 Thessalonians", 
                                        "1 Timothy", "2 Timothy",
                                        "Titus","Philemon",
                                        "Hebrews", "James", "1 Peter",
                                        "2 Peter", "1 John", "2 John",
                                        "3 John","Jude", "Revelation"), "New Testament", "Old Testament"))
```


```{r}
words_book <- bible %>% 
  group_by(book, testament) %>% 
  summarise(characters = sum(nchar(text))) %>% 
  arrange(-characters) %>% 
  pull(book)

words_testament <- bible %>% 
  group_by(book, testament) %>% 
  summarise(characters = sum(nchar(text))) %>% 
  arrange(-characters) %>% 
  pull(testament)
```


```{r}
bible_words <- bible %>% 
  unnest_tokens(word, text) %>% 
  anti_join(stop_words) %>% 
  mutate(word = wordStem(word))

words_rate <- bible_words %>% 
  group_by(testament) %>% 
  count(word, sort = TRUE) %>% 
  left_join(bible_words %>% 
              group_by(testament) %>% 
              summarise(total = n())) %>% 
  mutate(rate = n/total) %>% 
  select(testament, word, rate) %>% 
  pivot_wider(names_from = "testament", values_from = "rate") 

plot <- words_rate %>% 
  ggplot(aes(`Old Testament`, `New Testament`, 
              color = abs(`New Testament` - `Old Testament`))) +
  geom_jitter(alpha = 0.1, 
              size = 2.5, 
              width = 0.3, 
              height = 0.3,
              na.rm = T) +
  geom_text(aes(label = word), 
            size = 4.5,
            check_overlap = TRUE, 
            vjust = 1.5,
            na.rm = T) +
  scale_x_log10(labels = percent_format()) +
  scale_y_log10(labels = percent_format()) +
  geom_abline(color = "gray40", lty = 2) +
  scale_color_gradient(limits = c(0, 0.01), 
                       low = "#5ddc85",  # #ee8169
                       high = "#2e0f9b") +
  labs(title = "Words Distribution in the Old and New Testament",
       caption = "Graphic: Sung Inkyung") +
  theme_minimal() +
  theme(legend.position="none") +
  ggsave(here::here("2020", "1213", "1213_WordsRateinOld&New.png"), width = 18, height = 12, units = "cm")
```

```{r}
words_rate %>% 
  filter(word %in% c('god', 'lord', 'faith', 'discipl', 'grace'))
```

