---
title: "FearTrust"
author: "Sung Inkyung"
date: '2021 5 1'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Source[30DayChartChallenge by Cara Thompson] (https://github.com/cararthompson/30DayChartChallenge/blob/main/scripts/1.3_historical.R)
```{r}
library(tidyverse)
library(tidytext)
library(ggtext)
library(ggwordcloud)
library(cowplot)
library(here)
```


```{r}
bible <- readr::read_csv("C:/Users/inkyscope/Documents/projects/data/bible_kjv_new.csv") 

bible_stop_words <- c(c("art", "thy", "thou", "thine", "thee", "hast", "hath","shalt",
                         "ye", "yea", "saith", "thereof", "wherefore", "lo", "aaron", "aaron's", "aaronites", "abarim")) 

df_nrc <- get_sentiments("nrc") %>% 
  filter(sentiment %in% c("trust", "fear"))
```


```{r}
df <- bible %>% 
  select(book, text) %>% 
  unnest_tokens(word, text) %>% 
  filter(!word %in% bible_stop_words) %>% 
  anti_join(stop_words, by = "word") %>% 
  inner_join(df_nrc, by = "word") %>% 
  count(sentiment, word, sort = T) %>% 
  group_by(sentiment) %>% 
  slice_max(n, n = 300) 
 
```

```{r}
theme_sentiment <- function(){
  theme_minimal() +
  theme(legend.position = "none",
        panel.background = element_rect(fill = "#dbc6a9",
                                        colour = "#dbc6a9"),
        plot.background = element_rect(fill = "#dbc6a9",
                                       colour = "#dbc6a9"),
        panel.grid = element_blank(),
        plot.title = element_markdown(hjust = 0.5, 
                                      size = 25, 
                                      colour = "#420420"),
        plot.caption = element_text(color = "#420420", size = 10),
        axis.text = element_blank(),
        axis.title = element_blank(),
        axis.ticks = element_blank())
}
```

```{r}

plot_fear <- ggplot(data = filter(df, sentiment == "fear"),
                 aes(label = word, size = n)) +
  geom_text_wordcloud_area(mask = png::readPNG("C:/Users/inkyscope/Documents/projectR/inkyscroll/data/letter_f.png"),
                           rm_outside = T,
                           color = "#555555",
                           shape = "square") +
  scale_size_area(max_size = 36) +
  theme_sentiment()

plot_trust <-ggplot(data = df %>% 
                      filter(sentiment == "trust"),
                    aes(label = word, size = n)) +
  geom_text_wordcloud_area(mask = png::readPNG("C:/Users/inkyscope/Documents/projectR/inkyscroll/data/letter_t.png"),
                           rm_outside = T,
                           color = "#555555",
                           shape = "square") +
  scale_size_area(max_size = 36) +
  theme_sentiment() 

title <- ggdraw() +
  draw_label("Top 300 Words \nRelating to FEAR and TRUST \nin the King James Bible",
             color = "#420420",
             hjust = .5, 
             size = 16) +
  theme_sentiment()

caption <- ggdraw() +
  draw_label("Source: NRC | Graphic: Sung Inkyung",
             color = "#420420",
             size = 8,
             hjust = .5) +
  theme_sentiment()

p <- plot_grid(title, 
               plot_grid(plot_fear, plot_trust, 
                         nrow = 1, rel_widths = c(.5, .5)),
               caption,
               ncol = 1, 
               rel_heights = c(.2, .7, .1))

ggsave(plot = p, filename = file.path("../W18_WordMask", "FearTrustMask.png"), 
       dpi = 400, width = 9.05, height = 7)
```
