---
title: "Gospel"
author: "Sung Inkyung"
date: '2019 11 1 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidytext)
library(ggtext)
library(cowplot)
library(patchwork)

```


```{r}
bible <- readr::read_csv("C:/Users/inkyscope/Documents/projects/data/bible_kjv_new.csv") 

gospel <- bible %>% 
  filter(book %in% c("Matthew", "Mark", "John", "Luke"))    
```
theme_update(rect = element_rect(fill = "#f2eadf"),
             panel.border = element_rect(color = "grey55", 
                                        size = 2),
            panel.background = element_rect(fill = "grey85", 
                                       colour = NA))

```{r ngram Analysis}
gospel_word <- gospel %>% 
  unnest_tokens(word, text) %>% 
  anti_join(stop_words) %>% 
  filter(!str_detect(word, "[0-9]"),
         !str_detect(word, "ye|jesus|god|thou|saith|lord|thy|thee|thee|hath|jews|jerusalem")) 

gospel_chapter <- gospel %>% 
  filter(book == "Matthew") %>% 
  group_by(book, chapter) %>% 
  unnest_tokens(word, text) %>% 
  anti_join(stop_words) %>% 
  filter(!str_detect(word, "[0-9]"),
         !str_detect(word, "ye|jesus|god|thou|saith|lord|thy|thee|thee|hath|jews|jerusalem")) %>% 
count(chapter, word, sort = TRUE) %>% 
  summarise(total = sum(n))
```


```{r ngram Analysis}
p <- gospel_word %>% 
  group_by(book) %>% 
  count(word, sort = TRUE) %>% 
  top_n(20) %>% 
  ungroup() %>% 
  mutate(book = fct_reorder(book, n)) %>% 
  ggplot(aes(word, n, fill = book)) + 
  geom_col() +
  facet_wrap(~book, scales = "free_y") +
  labs(x = "",
       y = "Frequency") +
  coord_flip() +
  theme(legend.position = "none")
```


```{r ngram Analysis}
# calculate percent of word use across 5 books

gospel_pct <- gospel %>% 
  unnest_tokens(word, text) %>% 
  anti_join(stop_words) %>% 
  count(word) %>% 
  transmute(word, all_words = n / sum(n))

# calculate percent of word use within each book
frequency <-gospel %>% 
  unnest_tokens(word, text) %>% 
  anti_join(stop_words) %>% 
  count(book, word) %>% 
  mutate(book_words = n / sum(n)) %>% 
  left_join(gospel_pct) %>% 
  arrange(desc(book_words)) %>% 
  ungroup() %>% 
  filter(!str_detect(word, "[0-9]"),
         !str_detect(word, "ye|jesus|god|thou|saith|lord|thy|thee|thee|hath|jews|jerusalem")) %>% 
  group_by(book) %>% 
  top_n(1000, n)



p <- frequency %>% 
  ungroup() %>% 
  ggplot(aes(book_words, all_words,
             color = abs(all_words - book_words)))+
  geom_jitter(alpha = 0.1,
              size = 1.5,
              width = 0.3,
              height = 0.3,
              show.legend = FALSE) +
  geom_abline(color = "gray50", lty = 2) +
  geom_text(aes(label = word), 
            check_overlap = TRUE, 
            vjust = 1,
            show.legend = FALSE) +
  scale_x_log10(labels = scales::percent_format()) +
  scale_y_log10(labels = scales:: percent_format()) +
  scale_color_gradient(limits = c(0, 0.001),
                       low = "#024500",
                       high = "#425e78") +
  facet_wrap(~book, ncol = 2) +
  theme(legend.position = "none") +
  labs(x = "% of word within each book",
       y = "% of word across all book",
       title = "Frequency for each word across 4 Gospels of new testament versus within each Gospel",
       subtitle = "Words such as son, day are close to the line, which means fairly common across four gospels. <br>As well, words can illustrate on a similarity and yet distinguishable perspective in each gospel. <br>For example, John tends to focus on the relationship between son and father, Mark on disciples") +
  theme(legend.position = "none",
        plot.title = element_markdown(size = 18),
        plot.subtitle = element_markdown(size = 13),
        plot.margin = margin(12, 6, 12, 18)) +
  theme_minimal()

p

frequency %>% 
  group_by(book) %>% 
  summarise(correlation = cor(book_words, all_words),
            p_value = cor.test(book_words, all_words)$p.value) 
 # The high correlations, which are statistically significant(p-values < 0.0001) except John, suggests that the relationship between the word frequencies is highly similar across Matthew, Mark, and Luke. 
```
### http://uc-r.github.io/sentiment_analysis
```{r}
get_sentiments("afinn")
get_sentiments("bing")
get_sentiments("nrc")
```


```{r}
gospel_nrc <- gospel_word %>% 
  right_join(get_sentiments("nrc")) %>% 
  filter(!is.na(sentiment)) %>% 
  count(sentiment, sort = TRUE)

gospel_word %>% 
  group_by(book) %>% 
  mutate(word_count = 1:n(),
         index = word_count %/% 200 + 1) %>% 
  inner_join(get_sentiments("bing")) %>% 
  count(book, index = index, sentiment) %>% 
  ungroup() %>% 
  pivot_wider(names_from = sentiment, values_from = n) %>% 
  mutate(sentiment = positive - negative,
         book = factor(book)) %>% 
  ggplot(aes(index, sentiment, fill = book)) +
  geom_col(alpha = 0.5,
           show.legend = FALSE)+
  facet_wrap(~book, ncol = 2, scales = "free_x") +
  theme_minimal()
  
    
```


```{r}
bing_word <- gospel_word %>% 
  inner_join(get_sentiments("bing")) %>% 
  count(word, sentiment, sort = TRUE) %>% 
  ungroup()

bing_word %>% 
  group_by(sentiment) %>% 
  top_n(10) %>% 
  ggplot(aes(reorder(word, n), n, fill = sentiment)) +
  geom_col(alpha = 0.7,
           show.legend = FALSE) +
  scale_fill_manual(values = c("#f3a09d", "#55c671")) +
  facet_wrap(~sentiment, scales = "free_y") +
  labs(x = "",
       y = "contribution to sentiment") +
  coord_flip()

```

```{r}
five <- bible %>% 
  filter(book %in% c("Matthew", "Mark", "John", "Luke", "Acts")) 

five_words <- five %>% 
  unnest_tokens(word, text) %>% 
  anti_join(stop_words) %>% 
  count(book, word, sort = TRUE) %>% 
  ungroup()

series_words <- five_words %>% 
  group_by(book) %>% 
  summarise(total = sum(n))

five_words <- left_join(five_words, series_words)

five_words %>% 
  mutate(ratio = n / total) %>% 
  ggplot(aes(ratio, fill = book)) + 
  geom_histogram(show.legend = FALSE) + 
  scale_x_log10() +
  facet_wrap(~book, ncol = 2)

```


```{r Zipf's Law}

freq_by_rank <- five_words %>% 
  group_by(book) %>% 
  mutate(rank = row_number(),
         frequency = n / total) 

freq_by_rank %>% 
  ggplot(aes(rank, frequency, color = book)) +
  geom_line() +
  scale_x_log10() +
  scale_y_log10()
```

```{r}
lower_rank <- freq_by_rank %>% 
  filter(rank < 500)

lm(log10(frequency) ~log10(rank), data = lower_rank)
```

```{r}
freq_by_rank %>% 
  ggplot(aes(rank, frequency, color = book)) +
  geom_abline(intercept = -1.2220, 
              slope = -0.7817,
              color = "gray50",
              linetype = 2) +
  geom_line(size = 1.2, alpha = 0.7) +
  scale_x_log10() +
  scale_y_log10()
```


```{r Inverse Document Frequency and tf-idf}

five_words_tf_idf <- five_words %>% 
  bind_tf_idf(word, book, n) %>% 
  arrange(desc(tf_idf))

five_words_tf_idf %>% 
  arrange(desc(tf_idf)) %>% 
  mutate(word = factor(word, levels = rev(unique(word)))) %>% 
  group_by(book) %>% 
  top_n(15, wt = tf_idf) %>% 
  ungroup() %>% 
  ggplot(aes(word, tf_idf, fill = book)) +
  geom_col(alpha = 0.7,
           show.legend = FALSE) +
  labs(x = "",
  y = "tf-idf",
  title = "Highest tf_idf words in 4 gospels and Acts") +
  facet_wrap(~book, ncol = 2, scales = "free") +
  coord_flip()
```


```{r}
library(drlib)

gospel %>% 
  filter(!str_detect(text, "[0-9]"),
         !str_detect(text, "ye|jesus|god|thou|saith|lord|thy|thee|thee|hath|jews|jerusalem")) %>% 
  unnest_tokens(bigram, text, token = "ngrams", n = 2) %>% 
  separate(bigram, c("word1", "word2"), sep = " ") %>% 
  filter(!word1 %in% stop_words$word,
         !word2 %in% stop_words$word) %>% 
  count(book, word1, word2, sort = TRUE) %>% 
  unite("bigram", c(word1, word2), sep = " ") %>% 
  group_by(book) %>% 
  top_n(10) %>% 
  ungroup() %>% 
  mutate(book = factor(book) %>% forcats::fct_rev()) %>%
        ggplot(aes(drlib::reorder_within(bigram, n, book), n, fill = book)) +
        geom_col(alpha = 0.7, 
                 show.legend = FALSE) +
        drlib::scale_x_reordered() +
  facet_wrap(~book, ncol = 2, scales = "free") +
  coord_flip()+
  labs(x = "",
       y = "")
  
```


```{r}
afinn <- get_sentiments("afinn")

nots <- gospel %>%
  filter(!str_detect(text, "[0-9]"),
         !str_detect(text, "ye|jesus|god|thou|saith|lord|thy|thee|thee|hath|jews|jerusalem")) %>% 
  unnest_tokens(bigram, text, token = "ngrams", n = 2) %>% 
  separate(bigram, c("word1", "word2"), sep = " ") %>% 
  filter(word1 == "not") %>% 
  inner_join(afinn, by = c(word2 = "word")) %>% 
  count(word2, value, sort = TRUE)
  
```


```{r}
nots %>% 
  mutate(contribution = n * value) %>% 
  arrange(desc(abs(contribution))) %>% 
  head(20) %>% 
  ggplot(aes(reorder(word2, contribution), n*value, fill = n*value > 0)) +
  geom_col(show.legend = FALSE) +
  labs(x = "Words preceded by 'not",
       y = "Sentiment value * # of occurrences") +
  coord_flip()
```
```{r}
negation_words <- c("not", "no", "never")

negated <- gospel %>% 
  filter(!str_detect(text, "[0-9]"),
         !str_detect(text, "ye|jesus|god|thou|saith|lord|thy|thee|thee|hath|jews|jerusalem")) %>% 
  unnest_tokens(bigram, text, token = "ngrams", n = 2) %>% 
  separate(bigram, c("word1", "word2"), sep = " ") %>% 
  filter(word1 %in% negation_words) %>% 
  inner_join(afinn, by = c(word2 = "word")) %>% 
  count(word1, word2, value, sort = TRUE) %>% 
  ungroup()

negated %>% 
  mutate(contribution = n *value) %>% 
  arrange(desc(abs(contribution))) %>% 
  group_by(word1) %>% 
  top_n(10, abs(contribution)) %>% 
  ggplot(aes(drlib::reorder_within(word2, contribution, word1), contribution, fill = contribution > 0)) +
   geom_col(show.legend = FALSE) +
  drlib::scale_x_reordered() +
  labs(x = "Words preceded by 'not",
       y = "Sentiment value * # of occurrences") +
  coord_flip()+
  facet_wrap(~ word1, scales = "free") 
  
```

```{r}
library(ggraph)
library(igraph)
library(widyr)

word_pairs <- gospel_word %>% 
  pairwise_count(word, chapter, sort = TRUE)

word_pairs %>% 
  filter(item1 == "son")

set.seed(2919)  

word_cor <- gospel_word %>% 
  group_by(word) %>% 
  filter(n() >= 15) %>% 
  pairwise_cor(word, chapter) %>% 
  filter(!is.na(correlation)) %>% 
  arrange(desc(correlation)) %>% 
  filter(correlation > 0.65) %>% 
  graph_from_data_frame() %>% 
  ggraph(layout = "fr") +
  geom_edge_link(aes(edge_alpha = correlation),
                 show.legend = FALSE) +
  geom_node_point(color = "lightblue",
                  size = 5) +
  geom_node_text(aes(label = name), repel = TRUE) +
  theme_void()

```

