---
title: "Network in Job"
author: "sung inkyung"
date: '2020 06 17'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## sources: http://uc-r.github.io/tidy_text
```{r}
library(tidyverse)
library(tidytext)
library(ggtext)

```

```{r}
job <- readr::read_csv("C:/Users/inkyscope/Documents/projects/data/bible_kjv_new.csv") %>% 
    filter(book == "Job") %>% 
    select(-c(citation, verse)) 
```


```{r Word Correlation}
library(widyr)
library(ggraph)

job_words <- job %>% 
  unnest_tokens(word, text) %>% 
  filter(!word %in% stop_words$word) %>% 
  filter(!word %in% c("thee", "thy", "hast", "thou", "thine", "wilt", "hast", "hath", "ye", "doth", "canst", "thereof","yea", "shalt", "a", "uz"))

```


```{r}
word_cors <- job_words %>% 
  group_by(chapter, word) %>% 
  pairwise_cor(word, chapter, sort = TRUE) %>% 
  filter(correlation > 0.5)
```

```{r}
word_cors %>% 
  filter(item1 == "hearts")
```

```{r}
word_cors %>% 
  filter(item1 %in% c("trouble", "upright", "justify", "pain")) %>% 
  group_by(item1) %>% 
  slice(1:5) %>% 
  ungroup() %>% 
  mutate(item2 = reorder(item2, correlation)) %>% 
  ggplot(aes(correlation,item2, fill = item1)) +
  geom_bar(stat = "identity",
           alpha = .7,
           show.legend = FALSE) + 
  scale_fill_brewer(palette = "Dark2") +
  scale_x_continuous(limits = c(0, 1),
                     breaks = seq(0, 1, 0.2)) +
  facet_wrap(~item1, scales = "free") +
  guides(fill = guide_legend(reverse = TRUE)) +
  theme_minimal()
```

```{r}
library(igraph)
library(ggraph)


set.seed(2020)

word_cors %>%  
  filter(item1 %in% c("trouble", "upright", "justify", "pain", "pity", "dwelling", "integrity", "hearts")) %>% 
  group_by(item1) %>% 
  slice(1:15) %>% 
  ungroup() %>% 
  mutate(item2 = reorder(item2, correlation)) %>% 
  graph_from_data_frame() %>% 
  ggraph(layout = "kk") + # graphopt
  geom_edge_link(aes(edge_alpha = correlation), 
                 show.legend = FALSE)+
  geom_node_point(color = "#575f8a", size = 4) +
  geom_node_text(aes(label = name),
                 repel = TRUE) +
  labs(title = "Word-pairs in Job ",
       subtitle = "Correlated words with selected words; dwelling, hearts, integrity, justify, pain, pity, trouble, upright",
       caption = "Source: King James Bible | Graphic: Sung Inkyung") +
  theme_void() 
```
