---
title: "Psalmswordpairs"
author: "sung inkyung"
date: '2019 8 7 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## sources: [Textminng](http://uc-r.github.io/tidy_text)
```{r}
library(tidyverse)
library(tidytext)
library(ggtext)
library(patchwork)
library(here)
```

```{r}
Psalms <- readr::read_csv("C:/Users/inkyscope/Documents/projects/data/bible_kjv_new.csv") %>% 
  filter(book == "Psalms") 
```

```{r}
tidy_psalms <- Psalms %>%
  select(chapter, text) %>% 
  unnest_tokens(word, text) %>%
  anti_join(stop_words) %>%
  group_by(word, chapter) %>%
  count(word, sort = TRUE) %>% 
  ungroup() %>% 
  filter(!word %in% c("thou", "thy", "thine", "hast", "art",
                      "shalt", "thee", "hath", "ye", "lord", "god" ))

```

```{r}
tidy_psalms %>% 
  count(word, sort = TRUE) %>% 
  filter( n > 40) %>% 
  mutate(word = reorder(word, n)) %>% 
  ggplot(aes(word, n)) +
  geom_col() +
  xlab(NULL) +
  coord_flip() +
  theme_minimal() 
```

```{r}
psalms_words <- tidy_psalms %>% 
  bind_tf_idf(word, chapter, n) %>% 
  arrange(desc(tf_idf))

psalms_words
```

```{r}
psalms_words %>% 
  arrange(desc(tf_idf)) %>% 
  mutate(word = factor(word, levels = rev(unique(word)))) %>% 
  top_n(15, tf_idf) %>% 
  filter(!word %in% c("praise", "aha")) %>% 
  ungroup() %>% 
  ggplot(aes(word, tf_idf)) +
  geom_col(show.legend = FALSE) +
  labs(x = NULL,
       y = "tf-idf") +
  coord_flip() +
  theme_minimal()
```

```{r}
Psalms_divided <- psalms_words %>% 
  mutate(
    chapter = case_when(
      chapter < 42 ~ "Book1",
      chapter < 73 ~ "Book2",
      chapter < 90 ~ "Book3",
      chapter < 107 ~ "Book4",
      chapter <= 150 ~ "Book5",
      TRUE ~ as.character(chapter)))
```

```{r}
Psalms_divided %>% 
  group_by(chapter) %>% 
  top_n(15, tf_idf)%>% 
  arrange(desc(tf_idf)) %>% 
  ungroup() %>% 
  mutate(word = fct_reorder(word, tf_idf, na.rm = TRUE)) %>%  
  ggplot(aes(word, tf_idf, fill = chapter)) +
  geom_col(alpha = .7,
           show.legend = FALSE) +
  scale_fill_brewer(palette = "Dark2") +
  coord_flip() +
  facet_wrap(~chapter, ncol = 2, scales = "free") +
  theme_minimal()+
  labs(x = "",
       y = "") 
```

```{r bigrams}
Psalms_books <- Psalms %>% 
  mutate(
    chapter = case_when(
      chapter < 42 ~ "Book1",
      chapter < 73 ~ "Book2",
      chapter < 90 ~ "Book3",
      chapter < 107 ~ "Book4",
      chapter <= 150 ~ "Book5",
      TRUE ~ as.character(chapter))) 
```

```{r}
psalms_bigrams <- Psalms_books %>% 
  select(chapter, text) %>% 
  unnest_tokens(bigram, text, token = "ngrams", n = 2) %>% 
  filter(!bigram %in% c("thou hast", "thou art", "thou shalt", "thou wilt")) %>% 
  separate(bigram, c("word1", "word2", sep = " ")) %>% 
  filter(!word1 %in% stop_words$word,
         !word2 %in% stop_words$word) %>% 
  count(chapter, word1, word2, sort = TRUE) %>% 
  unite(bigram, word1, word2, sep = " ") 
```

```{r}
psalms_bigrams %>% 
  arrange(desc(n)) %>% 
  group_by(chapter) %>% 
  top_n(10) %>% 
  ungroup() %>% 
  mutate(bigram = drlib::reorder_within(bigram, n, chapter)) %>% 
  ggplot(aes(bigram, n, fill = chapter)) +
  geom_col(stat = "identity", 
           alpha = .7,
           show.legend = FALSE) +
  scale_fill_brewer(palette = "Dark2") +
  facet_wrap(~chapter, ncol = 2, 
             scales = "free") +
  drlib::scale_x_reordered()+
  coord_flip() +
  theme_minimal()
```

```{r}
# Analyzing bigrams

bigrams_tf_idf <- psalms_bigrams %>% 
  count(chapter, bigram, sort = TRUE) %>% 
  bind_tf_idf(bigram, chapter, n) %>% 
  arrange(desc(tf_idf))

bigrams_tf_idf$facet = factor(bigrams_tf_idf$chapter, 
                              levels = c("Book1", "Book2", "Book3", "Book4", "Book5"))
```

```{r}
bigrams_tf_idf %>% 
  group_by(chapter) %>% 
  sample_n(10, wt = tf_idf) %>% 
  ungroup() %>% 
  mutate(chapter = factor(chapter) %>% 
           forcats::fct_rev()) %>% 
  ggplot(aes(drlib::reorder_within(bigram, tf_idf, chapter, na.rm = TRUE), 
             tf_idf, fill =chapter)) +
  geom_bar(stat = "identity", alpha = .7, 
           show.legend = FALSE) +
  labs(title = "Highest tf-idf bigrams in Psalms", 
       x = " ",
       y = "") +
  drlib::scale_x_reordered() +
  facet_wrap(~ facet, ncol = 2, scales = "free") +
  coord_flip()+
  theme_minimal()
```

```{r}
psalms_bigrams <- Psalms_books %>% 
  unnest_tokens(bigram, text, token = "ngrams", n = 2) %>% 
  separate(bigram, c("word1", "word2"), sep = " ") 
```

```{r}
library(textdata)

psalms_bigrams %>% 
  filter(word1 == "not") %>% 
  count(word1, word2, sort = TRUE)

not_words <- psalms_bigrams  %>% 
  filter(word1 == "not") %>% 
  inner_join(get_sentiments("afinn"), 
             by = c(word2 = "word")) %>% 
  count(word2, value, sort = TRUE) 

not_words
```

```{r}
p1 <- not_words %>% 
  mutate(contribution = n * value) %>% 
  arrange(desc(abs(contribution))) %>% 
  head(20) %>% 
  ggplot(aes(reorder(word2, contribution), n*value, 
             fill = n*value > 0))+
  geom_col(show.legend = FALSE) +
  coord_flip()+
  scale_fill_manual(values = c("#c6008e", "#1caa55")) +
  labs(title = "Words preceded by 'not' based on the contribution to sentiment values",
       x = " ",
       y = "Sentiment value * number of occurrences") +
  theme(plot.title = element_text(size = 24,
                                  margin = margin(b = 10)),
        axis.text.x = element_text(size = 7),
        axis.title.y = element_text(size = 9)) +
  theme_half_open(12)

p1
```

```{r}
negation_words <- c("not", "no", "never", "without")

negated_words <- psalms_bigrams %>% 
  filter(word1 %in% negation_words) %>%  
  inner_join(get_sentiments("afinn"), 
             by = c(word2 = "word")) %>% 
  count(word1, word2, value, sort = TRUE)

negated_words
```

```{r}
negated_words %>% 
  mutate(contribution = n*value) %>% 
  arrange(desc(abs(contribution))) %>% 
  group_by(word1) %>% 
  top_n(7, abs(contribution)) %>% 
  ggplot(aes(drlib::reorder_within(word2, contribution, word1),
             contribution, fill = contribution > 0)) +
  geom_col(alpha = .7,
           show.legend = FALSE) +
  scale_fill_manual(values = c("#c6008e", "#1caa55")) +
  labs(title = "Words preceded by 'never', 'no', 'not' based on the contribution to sentiment values",
       x = "",
       y = "Sentiment value * # of occurrences") +
    drlib::scale_x_reordered() +
  facet_wrap(~word1, scales = "free") +
  coord_flip() +
  theme_minimal()
```

```{r bigram Networks}
library(igraph)
library(ggraph)

count_bigrams <- function(dataset) {
  dataset %>%
    unnest_tokens(bigram, text, token = "ngrams", n = 2) %>%
    separate(bigram, c("word1", "word2"), sep = " ") %>%
    filter(!word1 %in% stop_words$word,
           !word2 %in% stop_words$word,
           !word1 %in% c("thou", "thy", "thine", "shalt", "art", 
                         "hath", "wilt", "hast", "ye", "yea")) %>%
    count(word1, word2, sort = TRUE)
}

visualize_bigrams <- function(bigrams) {
  set.seed(2019)
  
  a <- grid::arrow(type = "closed", length = unit(.2, "cm"))
  
  bigrams %>%
    graph_from_data_frame() %>%
    ggraph(layout = "fr") +
    geom_edge_link(aes(edge_alpha = n), show.legend = FALSE, arrow = a) +
    geom_node_point(color = "#ffaa55", size = 3) +
    geom_node_text(aes(label = name), 
                   vjust = 1, 
                   hjust = 1) +
    theme_void()
}
```

```{r}

library(ggtext)

psalms_bigrams <- Psalms %>%
  count_bigrams()

# filter out rare combinations, as well as digits
psalms_bigrams %>%
  filter(n > 3,
         !str_detect(word1, "\\d"),
         !str_detect(word2, "\\d")) %>%
  visualize_bigrams() +
  labs(title = "Common bigrams in the Psalms from King James Bible")
```

```{r Counting and correlating among sections}
library(widyr)

psalms_chapter_words <- Psalms %>% 
  mutate(chapter = row_number() %/% 10) %>% 
  filter(chapter > 0) %>% 
  unnest_tokens(word, text) %>% 
  filter(!word %in% stop_words$word) %>% 
  select(-c("citation", "verse"))

psalms_chapter_words
```

```{r}
# count words co-occuring within chapters
word_pairs <- psalms_chapter_words %>% 
  pairwise_count(word, chapter, sort = TRUE)

word_pairs
```

```{r}
word_pairs %>% 
  filter(item1 == "morning")
```

```{r}
word_cors <- psalms_chapter_words %>% 
  group_by(word) %>% 
  filter(n()>20) %>% 
  pairwise_cor(word, chapter, sort = TRUE)
```

```{r}
word_cors %>% 
  filter(item1 == "word")
```

```{r}
p2 <- word_cors %>% 
  filter(item1 %in% c("word", "mercy", "mouth", "enemy")) %>% 
  group_by(item1) %>% 
  top_n(8) %>% 
  ungroup() %>% 
  mutate(item2 = fct_reorder(item2, correlation)) %>% 
  ggplot(aes(item2, correlation, fill = item1)) +
  geom_bar(stat = "identity",
           alpha = .7,
           show.legend = FALSE) + 
  scale_fill_brewer(palette = "Set2") +
  facet_wrap(~item1, scales = "free") +
  coord_flip() +
  labs(title = "Most correlated words with given words:<br><span style = 'color:#66C2A5'>Enemy</span>, <span style = 'color:#FC8D62'> Mercy</span>, <span style = 'color:#8DA0CB'> Mouth</span>, <span style = 'color:#E78AC3'> Word</span>",
       x = "",
       y= "correlation") +
  theme_half_open(12) +
  theme(plot.title = element_markdown(size = 20,
                                      margin = margin(b = 10)),
        axis.text.x = element_text(size = 9))
 
```

```{r}
set.seed(2019)

p3 <- word_cors %>%  
  filter(correlation > .25,
         !item1 %in% c("thou", "thy", "thee", "thine", "shalt", "art", "hath", "wilt", "hast", "ye", "yea")) %>% 
  graph_from_data_frame() %>% 
  ggraph(layout = "fr") + # graphopt
  geom_edge_link(aes(edge_alpha = correlation,
                     edge_width = correlation), 
                 edge_color = "#213970") +
  geom_node_point(size = 3,
                  color = "#210070") +
  geom_node_text(aes(label = name), 
                 size = 4.5,
                 repel = TRUE,
                 point.padding = unit(0.2, "lines")) +
  labs(title = "Correlated Word Pairings in <span style = 'color:#210070'>**Psalms**</span>",
       subtitle = "Correlated words with higher than .25 correlation appearing within the same 10-line verses.<br>What brought to my attention is a cluster linked to **Word** on the bottom left such as precepts, statutes, commandments, <br> judgments, law, and testimonies.<br>**Love** is projecting from its cluster like a whisker or a tack push pin. Is it as the same in the other?",
       caption = "\nSource| kingjamesbibleonline.org") +
  theme(legend.position = "none",
        panel.background = element_rect(fill = "transparent"),
        plot.margin = margin(.7, .7, .7, .7, "inch"),
        plot.title = element_markdown(size = 24, 
                                  color = "#21130b",
                                  margin = margin(b = 10)),
        plot.subtitle = element_markdown(size = 16, 
                                         color = "#21130b",
                                         lineheight = 1.25,
                                  margin = margin(b = 20)),
        plot.caption = element_text(size = 11,
                                    color = "#162a41"))

```

