---
title: "NeverCombo"
author: "sung inkyung"
date: '2020 4 2'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## sources: [Textminng](http://uc-r.github.io/tidy_text)
```{r}
library(tidyverse)
library(tidytext)
library(ggtext)
library(highcharter)
library(here)
```

```{r}
Psalms <- readr::read_csv("C:/Users/inkyscope/Documents/projects/data/bible_kjv_new.csv") %>% 
  filter(book == "Psalms") 
```

```{r}
psalms_bigrams <- Psalms %>% 
  select(chapter, text) %>% 
  unnest_tokens(bigram, text, token = "ngrams", n = 2) %>% 
  filter(!bigram %in% c("thou hast", "thou art", "thou shalt", "thou wilt")) %>% 
  separate(bigram, c("word1", "word2", sep = " ")) %>% 
  filter(!word1 %in% stop_words$word,
         !word2 %in% stop_words$word) %>% 
  count(chapter, word1, word2, sort = TRUE) %>% 
  unite(bigram, word1, word2, sep = " ") 
```

```{r}
psalms_bigrams <- Psalms %>% 
  unnest_tokens(bigram, text, token = "ngrams", n = 2) %>% 
  separate(bigram, c("word1", "word2"), sep = " ") 
```


```{r}
negation_words <- c("not", "no", "never", "without")

negated_words <- psalms_bigrams %>% 
  filter(word1 %in% negation_words) %>%  
  inner_join(get_sentiments("afinn"), 
             by = c(word2 = "word")) %>% 
  count(word1, word2, value, sort = TRUE)

negated_words
```

```{r}

never_plot <- negated_words %>% 
  mutate(contribution = n*value) %>% 
  arrange(desc(abs(contribution))) %>% 
  group_by(word1) %>% 
  top_n(7, abs(contribution)) %>%
  filter(word1 == "never") %>% 
  hchart("bar",
         hcaes(y = contribution,
               x = word2)) %>% 
  hc_add_theme(hc_theme_chalk()) %>% 
  hc_title(text = "Words preceded by 'NEVER' based on the contribution to AFINN sentiment values",
           margin = 10,
           fontSize = "50px") %>% 
  hc_xAxis(title = list(text = NULL)) %>% 
  hc_yAxis(title = list(text = "Contribution (Frequency*AFINN Value)")) %>% 
  hc_credits(enabled = TRUE,
             text = "Granphic: Sung Inkyung",
             style = list(
               fontSize = "14px"
             )
  ) 

  #hc_exporting(enabled = TRUE, filename = "psalmsnever.png")


```
