---
title: "PsalmsSentiment"
author: "Sung Inkyung"
date: '2020.3.7 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Source[tidytuesday by gkaramanis] (https://github.com/gkaramanis/tidytuesday/blob/master/2020-week03/passwords-bsplines.R)
```{r}
library(tidyverse)
library(tidytext)
library(paletteer)
library(here)

```
### source [Sentiment Analysis in R] (http://rstudio-pubs-static.s3.amazonaws.com/283881_efbb666d653a4eb3b0c5e5672e3446c6.html)
```{r}
bible <- readr::read_csv("C:/Users/inkyscope/Documents/projects/data/bible_kjv_new.csv") %>% 
  filter(book == "Psalms")
```

```{r}
psalms <- bible %>% 
  select(-c("citation", "book", "verse")) %>% 
  mutate(verse_number = row_number()) %>% 
  unnest_tokens(word, text) %>% 
  anti_join(stop_words) %>% 
  filter(!word %in% psalms_stop_word,
         str_detect(word, "[a-z]"))

psalms_afinn <- psalms %>% 
  inner_join(get_sentiments("afinn")) %>% 
  filter(!is.na(value)) %>% 
  group_by(word, value) %>% 
  summarise(count = sum(n())) %>% 
  ungroup()
  

psamls_afinn <- 
  unique(psalms_afinn[order(psalms_afinn$value), ]) %>% 
  filter(count > 10) %>% 
  mutate(value = factor(value))

afinn_plot <- psalms_afinn %>% 
  ggplot() +
  geom_text(aes(value, count, label = word, color = value),
            check_overlap = FALSE) +
  scale_color_gradient(low = "#56b1f7",
                       high = "#eba487") +
  guides(color = FALSE) +
  labs(x = "AFINN value",
       y = "Count",
       title = "Sentiment analysis of Psalms using the AFINN lexicon",
       subtitle = "AFINN lexicon assigns words with a score that runs between -5 and 5, with negative scores indicating negative sentiment and positive scores indicating positive sentiment.",
       caption = "Source: King James Bible | Graphic: Sung Inkyung") +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 14, 
                              face = "bold",
                              color = "#f2f3f5",
                              margin = margin(t= 10, b = 8)),
    plot.background = element_rect(fill = "#1a1c2e"),
    plot.subtitle = element_text(size = 11, 
                                 lineheight = 1.1,
                                 color = "#e6e7eb",
                                 margin = margin(b = 20)),
    plot.caption = element_text(size = 9,
                                color = "#e6e7eb",
                                 margin = margin(t = 10)),
    panel.grid.minor.x = element_blank(),
    panel.grid.minor.y = element_blank(),
    panel.grid.major.y = element_line(color = "#21243a"),
    panel.grid.major.x = element_line(color = "#21243a"),
    axis.text = element_text(color = "#e6e7eb", size = 10),
    axis.text.x = element_text(margin = margin(t = 5)),
    axis.text.y = element_text(margin = margin(r = 5)),
    axis.title = element_text(size = 9, color = "#e6e7eb"),
    axis.title.y = element_text(margin = margin(r = 20),
                                hjust = 1),
    axis.ticks = element_line(color = "#babcd1"),
    axis.title.x = element_text(margin = margin(t = 15),
                                hjust = 1),
    axis.line = element_line(color = "#9d9fb0")
  )

ggsave(here("figures", "PsamlsAfinn.png"), width = 34, height = 24, units="cm")

```

```{r}

psalms_stop_word <- c(c("thy", "thou", "thine", "thee", "hast", "hath", "lord", "god", "ye", "yea"))

sent10equal = c("#BF4D91", "#634DBF",  "#FF4500", "#BF4D4D", "#Af9B81", "#D7CE17", "#63BF4D", "#BF914D", "#4D7ABF", "#4DBFBF")

psalms <- bible %>% 
  select(-c("citation", "book", "verse")) %>% 
  mutate(verse_number = row_number()) %>% 
  unnest_tokens(word, text) %>% 
  anti_join(stop_words) %>% 
  filter(!word %in% psalms_stop_word,
         str_detect(word, "[a-z]"))
  

psalms %>% 
  count(verse_number, sort = TRUE)

psalms_nrc <- psalms %>% 
  inner_join(get_sentiments("nrc")) %>% 
  filter(!is.na(sentiment)) %>% 
  group_by(sentiment, word) %>% 
  summarise(frequency = n()) %>% 
  ungroup() %>% 
  mutate(sentiment = factor(sentiment),
         sentiment = fct_reorder(sentiment, frequency)) %>% 
  filter(frequency >= 3)

```

```{r}
bsplines <- psalms_nrc %>% 
  mutate(
    r = frequency/100,
    x = lapply(r/2, function(x)
    {y = rnorm(4, 1, r/5)
    x*c(-1, 1, 1, -1) + y}),
    y = lapply(r/2, function(x)
    {y = rnorm(4, 1, r/5)
    x*c(1, 1, -1, -1) + y})
    ) %>%
  unnest()
```
```{r}
bsplines %>% 
  ggplot() +
  geom_bspline_closed(aes(x, y, group = word, 
                          color = frequency, 
                          size = frequency), 
                      fill = NA) +
  scale_color_paletteer_c("pals::isol")+
  scale_size(range = c(0, 0.7), guide = FALSE) +
  labs(x = "",
       y = "",
       title = "Classification of 10 sentiments of words extracted from Psalms book by NRC lexicon",
       subtitle = "Every circle is a word. Radius, stroke width, and color represent its frequency through 150 chapters.",
       caption = "Graphic: Sung Inkyung")+
   guides(color = guide_colorbar(title = "Frequency", 
                         title.position = "top", 
                         title.hjust = 0.5, 
                         barheight = 0.7)) +
  facet_wrap(vars(toupper(sentiment)), ncol = 5) +
  coord_fixed() +
  theme_void() +
  theme(
    legend.position = "bottom",
    plot.title = element_text(size = 16, hjust = 0.5, 
                              margin = margin(b = 20)),
    plot.subtitle = element_text(size = 12, hjust = 0.5, 
                                 margin = margin(b = 50)),
    plot.caption = element_text(size = 8,  color = "grey60",
                                margin = margin(0, 0, 0, 0)),
    strip.text = element_text(size = 9, 
                              color = "#484e4a", 
                              margin = margin(b = 10)),
    plot.margin = margin(10, 10, 10, 10)
  )

ggsave(here("figures", "PsalmsSentimentsBisplines.png"), width = 24, height = 21, units = "cm")
```