---
title: "WordsParade"
author: "Sung Inkyung"
date: '2020 6 28 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidytext)
library(here)
```
### Source[tidytuesday by PMassicotte] (https://github.com/PMassicotte/tidytuesday/blob/master/R/tidytuesday_2020_week03.R)

```{r}
job <- readr::read_csv("C:/Users/inkyscope/Documents/projects/data/bible_kjv_new.csv") %>% 
    filter(book == "Job") %>% 
    select(-c(citation, verse)) 
```


```{r}
job_words <- job %>%
   mutate(
    character = case_when(
      chapter %in% c("1", "2") ~ "Satan",
    chapter %in% c("3", "6", "7", "9", "10", "12", "13", "14", "16", "17", "19", "21", "23", "24", "26", "27", "28", "29", "30", "31", "42") ~ "Job",
    chapter %in% c("4", "5", "15", "22") ~ "Eliphaz",
    chapter %in% c("8", "18", "25") ~"Bildad",
    chapter %in% c("11", "20") ~ "Zophar",
    chapter %in% c("32", "33", "34", "35", "36", "37") ~"Elihu",
    chapter %in% c("38", "39", "40", "41") ~ "God",
    TRUE ~ as.character(chapter)
    )) %>% 
  unnest_tokens(word, text) %>%
  anti_join(stop_words) %>%
  filter(!word %in% c("thou", "thy", "thine", "hast", "art",
                      "shalt", "thee", "hath", "ye", "yea", "thereof", "job", "god", "day", "doth", "canst", "cometh", "wilt", "shouldest", "uz")) %>% 
  add_count(word) %>% 
  filter(n > 30)
 


jw <- job_words %>% 
  group_by(character, add = T) %>% 
  group_nest() %>% 
  mutate(t = map2(character, data, function(character, data) {
    data %>% 
      mutate(character = character) %>% 
      add_row(character = character) %>% 
      add_row(character = character) %>% 
      add_row(character = character)
  })) %>% 
  select(-character) %>% 
  unnest(t) %>% 
  rowid_to_column() %>% 
  mutate(word = fct_reorder(word, character)) 

label_data <- jw
number_of_bar <- nrow(label_data)
angle <- 90 - 360 * (label_data$rowid - 0.5) / number_of_bar
label_data$hjust <- ifelse(angle < -90, 0, 1)
label_data$angle <- ifelse(angle < -90, angle + 180, angle)
```


```{r}
char <- jw %>% 
  drop_na() %>% 
  group_nest(character) %>% 
  mutate(pos = map_dbl(data, ~mean(.$rowid, na.rm = T))) %>% 
  mutate(angle = 90 - 360 * (pos - .5) / number_of_bar) %>% 
  mutate(angle2 = ifelse(angle < -90, angle + 180, angle)) %>% 
  mutate(hjust = ifelse(angle < -90, 0, 1))
```

##paletteer::scale_fill_paletteer_d("ggsci::default_jama")
```{r}
plot <- jw %>% 
  ggplot(aes(x = factor(rowid),
             y = n + 1, 
             fill = character)) +
  geom_col() +
  scale_y_continuous(limits = c(-50, 50), 
                     expand = c(0, 0)) +
  scale_x_discrete(expand = c(0, 0)) +
  coord_polar(start = 0) +
  geom_text(data = label_data,
            aes(x = factor(rowid),
                y = -1, 
                label = word,
                hjust = hjust),
            color = "gray90",
            size = .7,
            angle = label_data$angle) +
  geom_text(data = char,
            aes(x = pos, 
                y = -5,
                label = character,
                angle = angle2,
                color = character,
                hjust = hjust),
            size = 4) +
  annotate("text",
           x = 0, y = -50,
           label = "Words Parade\nin the Book of\nJob",
           color = "gray90",
           fontface = "bold",
           size = 8) +
  labs(caption = "Graphic: Sung Inkyung") +
  paletteer::scale_fill_paletteer_d("Redmonder::qMSOBu2") +
  paletteer::scale_color_paletteer_d("Redmonder::qMSOBu2") +
  theme(legend.position = "none",
        plot.background = element_rect(fill = "#091114"),
        panel.background = element_rect(fill = "#091114"),
        plot.caption = element_text(size = 11,
                                    color = "gray90",
                                    hjust = .5,
                                    margin = margin(b = 20)),
        panel.grid = element_blank(),
        panel.border = element_blank(),
        axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank())

ggsave(here("figures", "WordsParadeinJob.png"), width = 25, height = 25, units = "cm")
  
```

