---
title: "HOLY"
author: "Sung Inkyung"
date: '2020 11 18'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Source[tidytuesday by geo karamanis] (https://github.com/gkaramanis/tidytuesday/blob/master/2020-week08/food-consumption.R)
```{r}
library(tidyverse)
library(tidytext)
library(ggtext)
library(showtext)

font_add_google("Anton")
font_add_google("Saira Condensed")
font_add_google("Roboto")

showtext_opts(dpi = 320)
showtext_auto(enable = TRUE)
```

```{r}
df_holy <- bible <- readr::read_csv("C:/Users/inkyscope/Documents/projects/data/bible_kjv_new.csv") %>% 
  unnest_tokens(word, text) %>% 
  filter(word == "holy") %>% 
  count(book, word, name = "count") %>% 
  mutate(book = fct_reorder(book, count))

plot_holy <- df_holy %>% 
  ggplot(aes(count, book, label = count)) +
  geom_col(fill = "#7d9cb6", color = NA) +
  geom_text(data = df_holy %>% filter(count >= 10),family = "Roboto", size = 3.5, face = "bold", nudge_x = -0.9) +
  scale_x_continuous(breaks = seq(0, 100, 20)) +
  coord_cartesian(expand = c(0, 0)) +
  labs(x = "",
       y = "", 
       title = "Distribution of HOLY through Bible Books",
       caption = "Source: King James Version | Graphic: Sung Inkyung") +
  theme_minimal() +
  theme(legend.position = "none",
        plot.background = element_rect(fill = "#cbc4bc", color = NA),
        plot.title = element_text(family = "Anton", size = 32, hjust = 0.5, 
                                  margin = margin(b = 15)),
        plot.caption = element_text(family = "Saira Condensed", size = 13, hjust = 0.5, 
                                    margin = margin(t = 15)),
        axis.text.x = element_text(family = "Saira Condensed", size = 14),
        axis.text.y = element_text(family = "Saira Condensed",
                                   size = 15),
        panel.grid.major.x = element_line(size = 0.4, color = "gray90"),
        panel.grid.major.y = element_blank(),
        panel.grid.minor = element_blank(),
        plot.margin = margin(20, 20, 20, 20)) 

ggsave("1118_HolyinBible.png", width = 33, height = 30, units = "cm")
```


```{r}
bible_holy <- bible <- readr::read_csv("C:/Users/inkyscope/Documents/projects/data/bible_kjv_new.csv") %>% 
  unnest_tokens(word, text) %>% 
  filter(word == "holy") %>% 
  count(book, word, name = "count") %>% 
  add_count(word, wt = count, name = "word_total") %>% 
  arrange(-count) %>% 
  slice_max(n = 10, order_by = count) %>% 
  ungroup() %>% 
  mutate(n = -4:5) %>% 
  rowwise() %>% 
  mutate(
    x = list(c(-10, 0, 0, -10)),
    y = list(c(n*4 - 1.4, n*2 - .7, n*2 + .7, n*4 + 1.4))
  ) %>% 
  unnest(cols = c(x, y)) 

```

```{r}
plot <- bible_holy %>% 
  ggplot() +
  geom_rect(aes(xmin = -22, ymin = n*4 - 1.4,
                xmax = -10, ymax = n*4 + 1.4),
            fill = "black", 
            color = NA) +
  geom_polygon(aes(x, y, group = n),
               fill = "black", color = NA) +
  geom_rect(aes(xmin = 0, ymin = n*2 - .7,
                xmax = count/4, ymax = n*2 + .7),
            fill = "black", 
            color = NA) +
  geom_text(aes(-14.5, n*4, 
                label = book),
            size = 5.5,
            family = "Saira Condensed",
            fontface = "bold",
            color = "white",
            hjust = 0.5,
            check_overlap = T) +
  geom_text(aes(count/4, n*2, 
                label = count),
            size = 4.5,
            family = "Saira Condensed",
            fontface = "bold",
            color = "white",
            hjust = 1,
            check_overlap = T) +
  scale_x_continuous(breaks = seq(0, 100, 20)) +
  scale_y_reverse() +
  labs(x = "",
       y = "",
       title = "**H O L Y**",
       caption = "**Source**: King James Bible | **Graphic**: Sung Inkyung") +
  theme_minimal() +
  theme(
    plot.title = element_markdown(size = 25,
                                  family = "Anton",
                                  hjust = .5),
    plot.caption = element_markdown(size = 9,
                                    family = "Roboto",
                                    hjust = .5,
                                    color = "gray60"),
    panel.grid.minor.x = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.major.y = element_blank(),
    panel.grid.minor.y = element_blank(),
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    plot.margin = margin(20, 20, 20, 20)
  )
  
ggsave("1118_Holy.png", width = 20, height = 16, units = "cm")
```
