---
title: "PsalmsEmotionsFlow"
author: "Sung Inkyung"
date: '2019 10 25'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidytext)
library(textdata)
library(cowplot)
library(gganimate)
library(here)
```
### source [text mining by julia silge](https://www.tidytextmining.com/sentiment.html)
```{r}
bible <- readr::read_csv("C:/Users/inkyscope/Documents/projects/data/bible_kjv_new.csv")
```
```{r}

psalms_stop_word <- c(c("thy", "thou", "thine", "thee", "hast", "hath", "lord", "god", "ye", "yea"))

sent10equal = c("#BF4D91", "#634DBF",  "#FF4500", "#BF4D4D", "#Af9B81", "#D7CE17", "#63BF4D", "#BF914D", "#4D7ABF", "#4DBFBF")

psalms <- bible %>% 
  filter(book == "Psalms") %>% 
  select(-c(citation)) %>% 
  mutate(verse_number = row_number()) %>% 
  mutate(
      chapter = case_when(
      chapter < 42 ~ "Book1",
      chapter < 73 ~ "Book2",
      chapter < 90 ~ "Book3",
      chapter < 107 ~ "Book4",
      chapter <= 150 ~ "Book5",
      TRUE ~ as.character(chapter))) %>% 
  unnest_tokens(word, text) %>% 
  anti_join(stop_words) %>% 
  filter(!word %in% psalms_stop_word,
         str_detect(word, "[a-z]"))
  

psalms %>% 
  count(verse_number, sort = TRUE)

p <- psalms %>% 
  inner_join(get_sentiments("nrc")) %>% 
  filter(!is.na(sentiment)) %>% 
  group_by(sentiment) %>% 
  summarise(sum = n()) %>% 
  ungroup() %>% 
  mutate(sentiment = factor(sentiment),
         sentiment = fct_reorder(sentiment, sum)) %>% 
  ggplot(aes(sentiment, sum, group = sentiment, fill = sentiment)) +
  geom_col(show.legend = FALSE) +
  geom_text(aes(label = sum), 
            size = 3.5,
            hjust = 1.2) +
  coord_flip()+
  scale_fill_manual(values = sent10equal) +
  theme_minimal() +
  labs(x = "",
       y = "count")

p

```

```{r}
nrc_joy <- get_sentiments("nrc") %>% 
  filter(sentiment == "anticipation")

psalms %>% 
  inner_join(nrc_joy, by = "word") %>% 
  count(word, sort = TRUE)
```
```{r}
psalms_sentiment <- psalms %>% 
  inner_join(get_sentiments("bing")) %>% 
  count(chapter, index = verse_number %/% 16, sentiment) %>% 
  pivot_wider(names_from = sentiment, values_from = n) %>% 
  mutate(sentiment = positive - negative)

book_names <- c("Book1" = "Book1 (chapter1-41)",
                "Book2" = "Book2 (chapter42-72)",
                "Book3" = "Book3 (chapter 73-89)",
                "Book4" = "Book4 (chapter 90-106)",
                "Book5" = "Book5 (chapter 107-150)")

p <- psalms_sentiment %>% 
  ggplot(aes(index, sentiment, fill = chapter)) +
  geom_col(show.legend = FALSE)+
  facet_wrap(~ chapter, 
             ncol = 2,
             labeller = as_labeller(book_names),
             scales = "free_x")+
  labs(x = "",
       y = "",
       title = "Semtiment analysis of Psalms using BING lexicon") +
  theme_half_open(12)

p
```
```{r}
#afinn = -5:5, bing, nrc : binary approach

afinn <- psalms %>% 
  inner_join(get_sentiments("afinn")) %>% 
  group_by(index = verse_number %/% 16) %>% 
  summarise(sentiment = sum(value)) %>% 
  mutate(lexicon = "AFINN")

bing_nrc <- bind_rows(psalms %>% 
                        inner_join(get_sentiments("bing")) %>% 
                        mutate(lexicon = "BING"),
                      psalms %>% 
                        inner_join(get_sentiments("nrc") %>% 
                        filter(sentiment %in% c("positive", "negative"))) %>% 
                        mutate(lexicon = "NRC")) %>% 
  count(lexicon, index = verse_number %/% 16, sentiment) %>% 
  pivot_wider(names_from = sentiment, values_from = n, 
              values_fill = NULL) %>%  
  mutate(sentiment = positive - negative)

bind_rows(afinn, bing_nrc) %>% 
  ggplot(aes(index, sentiment, fill = lexicon)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~ lexicon, ncol = 1, scales = "free_y") +
  theme_half_open(12)
  
```
```{r}
get_sentiments("nrc") %>% 
  filter(sentiment %in% c("positive", "negative")) %>% 
  count(sentiment)

get_sentiments("bing") %>% 
  count(sentiment)
```
```{r}
bing_word_counts <- psalms %>% 
  inner_join(get_sentiments("bing")) %>% 
  count(word, sentiment, sort = TRUE) %>% 
  ungroup()

bing_word_counts %>% 
  group_by(sentiment) %>% 
  top_n(10) %>% 
  ungroup() %>% 
  mutate(word = reorder(word, n)) %>% 
  ggplot(aes(word, n, fill = sentiment)) +
  geom_col(show.legend = FALSE) +
  
  scale_fill_manual(values = c("#f3a09d", "#55c671")) +
  facet_wrap(~sentiment, scales = "free_y") +
  labs(x = "",
       y = " ",
       title = "Most common positive and negative words across 150 chapters of Psalms") +
  coord_flip() +
  theme_half_open()
```
```{r}
library(wordcloud)

psalms %>% 
  count(word) %>% 
  with(wordcloud(word, n, max.words = 100))
```
```{r}
psalms
```

```{r}
plot_sent <- psalms %>%
  inner_join(get_sentiments("nrc")) %>% 
  filter(str_detect(sentiment, "positive negative", 
                    negate = TRUE)) %>% 
  group_by(sentiment, chapter) %>% 
  mutate(sent_count_chapter = n()) %>% 
  ungroup() %>% 
  group_by(chapter) %>% 
  mutate(sum_chapter = n()) %>% 
  mutate(prop = sent_count_chapter / sum_chapter,
         prop = round(prop, 2),
         sentiment = str_to_title(sentiment)) %>% 
  arrange(chapter) 

plot_sent %>% 
  count(verse_number, sort = TRUE)
```


```{r}
base_plot <- plot_sent %>% 
  ggplot(aes(chapter, prop, 
             group = sentiment,
             color = sentiment)) +
  geom_line(size = 1.3,
            alpha = 0.7) +
  geom_text(aes(x = chapter, 
                label = sentiment),
            size = 5,
            hjust = 0) +
  scale_color_manual(values = sent10equal) +
  scale_x_discrete() +
  labs(x = "",
       y = "Percent of words",
       title = "Psalms Sentiments Flow From Chapter 1 to Chapter 150",
       subtitle = ("Using NRC lexicon, it divides into the category of the sentiment \nassociated with words in Psalms across chapters."),
       caption = "Source: kingjamesbibleonline.org | Visualization by sung inkyung") +
  theme(legend.position = "none",
        plot.background = element_rect(fill = "#191919"),
        panel.background = element_rect(fill = "#191919"),
        plot.title = element_text(color = "gray80",
                                  size = 28, 
                                  hjust = 0.5),
        plot.subtitle = element_text(color = "gray80",
                                     size = 18, 
                                     lineheight = 0.9,
                                     hjust = 0.5),
        plot.caption = element_text(size = 9,
                                    color = "#e5e6e0"),
        panel.grid = element_blank(),
        panel.grid.major.x = element_line(size = 0.5,
                                          linetype = 2,
                                          color = "#cdc0b0"),
        axis.text = element_text(color = "white", 
                                 size = 9),
        axis.title = element_text(size = 11),
        plot.margin = margin(12, 18, 12, 12)) 

base_plot

ggsave(here("2019", "1025_PsalmsEmotionsFlow", "1025_PsalmsEmotionsFlow.png"), width = 31, height = 21, units = "cm")
```

```{r}
animation <- base_plot +
  transition_reveal(
    along = verse_number,
    keep_last = TRUE) +
  ease_aes("linear")

animate(animation, width = 850, height = 450, 
        nframes = 170, 
        fps = 20, 
        end_pause = 10,
        renderer = gifski_renderer(here::here("2019", "1025_PsalmsEmotionsFlow", "1025_PsalmsEmotionsFlow.gif")))
```



